In [ ]:
import pandas as pd
import ssl
import certifi
import urllib.request
import io

def get_stats(year):

    url = f"https://www.basketball-reference.com/leagues/NBA_{year}.html"

    context = ssl.create_default_context(cafile=certifi.where())

    with urllib.request.urlopen(url, context=context) as response:
        html = response.read()

    tables = pd.read_html(io.BytesIO(html))

    if year <= 2015:
        advanced_stats = tables[8].copy()
    else:
        advanced_stats = tables[10].copy()

    return advanced_stats

#### commenting out advanced_2018 = get_stats(2018)
#### advanced_2001 = get_stats(2001)
##### advanced_2026 = get_stats(2026)

HTTPError: HTTP Error 429: Too Many Requests

In [ ]:
for name, table in enumerate(tables):
    print(name, table.columns.tolist())

0 ['Eastern Conference', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS']
1 ['Western Conference', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS']
2 ['Eastern Conference', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS']
3 ['Western Conference', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS']
4 ['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']
5 ['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']
6 ['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']
7 ['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']
8 ['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']
9 ['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']
10 [('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Team'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'W'), ('Unnamed: 4_level_0', 'L'), ('Unnamed: 5_level_0', 'PW'), ('Unnamed: 6_level_0', 'PL'), ('Unnamed: 7_level_0', 'MOV'), ('Unnamed: 8_level_0', 'SOS'), ('Unnamed: 9_level_0', 'SRS'), ('Unnamed: 10_level_0', 'ORtg'), ('Unnamed: 11_level_0', 'DRtg'), ('Unnamed: 12_level_0', 'NRtg'), ('Unnamed: 13_level_0', 'Pace'), ('Unnamed: 14_level_0', 'FTr'), ('Unnamed: 15_level_0', '3PAr'), ('Unnamed: 16_level_0', 'TS%'), ('Unnamed: 17_level_0', 'Unnamed: 17_level_1'), ('Offense Four Factors', 'eFG%'), ('Offense Four Factors', 'TOV%'), ('Offense Four Factors', 'ORB%'), ('Offense Four Factors', 'FT/FGA'), ('Unnamed: 22_level_0', 'Unnamed: 22_level_1'), ('Defense Four Factors', 'eFG%'), ('Defense Four Factors', 'TOV%'), ('Defense Four Factors', 'DRB%'), ('Defense Four Factors', 'FT/FGA'), ('Unnamed: 27_level_0', 'Unnamed: 27_level_1'), ('Unnamed: 28_level_0', 'Arena'), ('Unnamed: 29_level_0', 'Attend.'), ('Unnamed: 30_level_0', 'Attend./G')]
11 [('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Team'), ('Unnamed: 2_level_0', 'G'), ('Unnamed: 3_level_0', 'MP'), ('Unnamed: 4_level_0', 'FG%'), ('Unnamed: 5_level_0', 'Dist.'), ('Unnamed: 6_level_0', 'Unnamed: 6_level_1'), ('% of FGA by Distance', '2P'), ('% of FGA by Distance', '0-3'), ('% of FGA by Distance', '3-10'), ('% of FGA by Distance', '10-16'), ('% of FGA by Distance', '16-3P'), ('% of FGA by Distance', '3P'), ('Unnamed: 13_level_0', 'Unnamed: 13_level_1'), ('FG% by Distance', '2P'), ('FG% by Distance', '0-3'), ('FG% by Distance', '3-10'), ('FG% by Distance', '10-16'), ('FG% by Distance', '16-3P'), ('FG% by Distance', '3P'), ('Unnamed: 20_level_0', 'Unnamed: 20_level_1'), ("% of FG Ast'd", '2P'), ("% of FG Ast'd", '3P'), ('Unnamed: 23_level_0', 'Unnamed: 23_level_1'), ('Dunks', '%FGA'), ('Dunks', 'Md.'), ('Unnamed: 26_level_0', 'Unnamed: 26_level_1'), ('Layups', '%FGA'), ('Layups', 'Md.'), ('Unnamed: 29_level_0', 'Unnamed: 29_level_1'), ('Corner', '%3PA'), ('Corner', '3P%'), ('Unnamed: 32_level_0', 'Unnamed: 32_level_1'), ('1/2 Court', 'Att.'), ('1/2 Court', 'Md.')]
12 [('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Team'), ('Unnamed: 2_level_0', 'G'), ('Unnamed: 3_level_0', 'MP'), ('Unnamed: 4_level_0', 'FG%'), ('Unnamed: 5_level_0', 'Dist.'), ('Unnamed: 6_level_0', 'Unnamed: 6_level_1'), ('% of FGA by Distance', '2P'), ('% of FGA by Distance', '0-3'), ('% of FGA by Distance', '3-10'), ('% of FGA by Distance', '10-16'), ('% of FGA by Distance', '16-3P'), ('% of FGA by Distance', '3P'), ('Unnamed: 13_level_0', 'Unnamed: 13_level_1'), ('FG% by Distance', '2P'), ('FG% by Distance', '0-3'), ('FG% by Distance', '3-10'), ('FG% by Distance', '10-16'), ('FG% by Distance', '16-3P'), ('FG% by Distance', '3P'), ('Unnamed: 20_level_0', 'Unnamed: 20_level_1'), ("% of FG Ast'd", '2P'), ("% of FG Ast'd", '3P'), ('Unnamed: 23_level_0', 'Unnamed: 23_level_1'), ('Dunks', '%FGA'), ('Dunks', 'Md.'), ('Unnamed: 26_level_0', 'Unnamed: 26_level_1'), ('Layups', '%FGA'), ('Layups', 'Md.'), ('Unnamed: 29_level_0', 'Unnamed: 29_level_1'), ('Corner', '%3PA'), ('Corner', '3P%')]

In [ ]:
print(advanced_2001.shape)
print(advanced_2001.columns)
print(advanced_2018.shape)
print(advanced_2018.columns)
print(advanced_2026.shape)
print(advanced_2026.columns)

(30, 31)
MultiIndex([(  'Unnamed: 0_level_0',                  'Rk'),
            (  'Unnamed: 1_level_0',                'Team'),
            (  'Unnamed: 2_level_0',                 'Age'),
            (  'Unnamed: 3_level_0',                   'W'),
            (  'Unnamed: 4_level_0',                   'L'),
            (  'Unnamed: 5_level_0',                  'PW'),
            (  'Unnamed: 6_level_0',                  'PL'),
            (  'Unnamed: 7_level_0',                 'MOV'),
            (  'Unnamed: 8_level_0',                 'SOS'),
            (  'Unnamed: 9_level_0',                 'SRS'),
            ( 'Unnamed: 10_level_0',                'ORtg'),
            ( 'Unnamed: 11_level_0',                'DRtg'),
            ( 'Unnamed: 12_level_0',                'NRtg'),
            ( 'Unnamed: 13_level_0',                'Pace'),
            ( 'Unnamed: 14_level_0',                 'FTr'),
            ( 'Unnamed: 15_level_0',                '3PAr'),
            ( 'Unnamed: 16_level_0',                 'TS%'),
            ( 'Unnamed: 17_level_0', 'Unnamed: 17_level_1'),
            ('Offense Four Factors',                'eFG%'),
            ('Offense Four Factors',                'TOV%'),
            ('Offense Four Factors',                'ORB%'),
            ('Offense Four Factors',              'FT/FGA'),
            ( 'Unnamed: 22_level_0', 'Unnamed: 22_level_1'),
            ('Defense Four Factors',                'eFG%'),
            ('Defense Four Factors',                'TOV%'),
            ('Defense Four Factors',                'DRB%'),
            ('Defense Four Factors',              'FT/FGA'),
            ( 'Unnamed: 27_level_0', 'Unnamed: 27_level_1'),
            ( 'Unnamed: 28_level_0',               'Arena'),
            ( 'Unnamed: 29_level_0',             'Attend.'),
            ( 'Unnamed: 30_level_0',           'Attend./G')],
           )
(31, 31)
MultiIndex([(  'Unnamed: 0_level_0',                  'Rk'),
            (  'Unnamed: 1_level_0',                'Team'),
            (  'Unnamed: 2_level_0',                 'Age'),
            (  'Unnamed: 3_level_0',                   'W'),
            (  'Unnamed: 4_level_0',                   'L'),
            (  'Unnamed: 5_level_0',                  'PW'),
            (  'Unnamed: 6_level_0',                  'PL'),
            (  'Unnamed: 7_level_0',                 'MOV'),
            (  'Unnamed: 8_level_0',                 'SOS'),
            (  'Unnamed: 9_level_0',                 'SRS'),
            ( 'Unnamed: 10_level_0',                'ORtg'),
            ( 'Unnamed: 11_level_0',                'DRtg'),
            ( 'Unnamed: 12_level_0',                'NRtg'),
            ( 'Unnamed: 13_level_0',                'Pace'),
            ( 'Unnamed: 14_level_0',                 'FTr'),
            ( 'Unnamed: 15_level_0',                '3PAr'),
            ( 'Unnamed: 16_level_0',                 'TS%'),
            ( 'Unnamed: 17_level_0', 'Unnamed: 17_level_1'),
            ('Offense Four Factors',                'eFG%'),
            ('Offense Four Factors',                'TOV%'),
            ('Offense Four Factors',                'ORB%'),
            ('Offense Four Factors',              'FT/FGA'),
            ( 'Unnamed: 22_level_0', 'Unnamed: 22_level_1'),
            ('Defense Four Factors',                'eFG%'),
            ('Defense Four Factors',                'TOV%'),
            ('Defense Four Factors',                'DRB%'),
            ('Defense Four Factors',              'FT/FGA'),
            ( 'Unnamed: 27_level_0', 'Unnamed: 27_level_1'),
            ( 'Unnamed: 28_level_0',               'Arena'),
            ( 'Unnamed: 29_level_0',             'Attend.'),
            ( 'Unnamed: 30_level_0',           'Attend./G')],
           )
(31, 31)
MultiIndex([(  'Unnamed: 0_level_0',                  'Rk'),
            (  'Unnamed: 1_level_0',                'Team'),
            (  'Unnamed: 2_level_0',                 'Age'),
            (  'Unnamed: 3_level_0',                   'W'),
            (  'Unnamed: 4_level_0',                   'L'),
            (  'Unnamed: 5_level_0',                  'PW'),
            (  'Unnamed: 6_level_0',                  'PL'),
            (  'Unnamed: 7_level_0',                 'MOV'),
            (  'Unnamed: 8_level_0',                 'SOS'),
            (  'Unnamed: 9_level_0',                 'SRS'),
            ( 'Unnamed: 10_level_0',                'ORtg'),
            ( 'Unnamed: 11_level_0',                'DRtg'),
            ( 'Unnamed: 12_level_0',                'NRtg'),
            ( 'Unnamed: 13_level_0',                'Pace'),
            ( 'Unnamed: 14_level_0',                 'FTr'),
            ( 'Unnamed: 15_level_0',                '3PAr'),
            ( 'Unnamed: 16_level_0',                 'TS%'),
            ( 'Unnamed: 17_level_0', 'Unnamed: 17_level_1'),
            ('Offense Four Factors',                'eFG%'),
            ('Offense Four Factors',                'TOV%'),
            ('Offense Four Factors',                'ORB%'),
            ('Offense Four Factors',              'FT/FGA'),
            ( 'Unnamed: 22_level_0', 'Unnamed: 22_level_1'),
            ('Defense Four Factors',                'eFG%'),
            ('Defense Four Factors',                'TOV%'),
            ('Defense Four Factors',                'DRB%'),
            ('Defense Four Factors',              'FT/FGA'),
            ( 'Unnamed: 27_level_0', 'Unnamed: 27_level_1'),
            ( 'Unnamed: 28_level_0',               'Arena'),
            ( 'Unnamed: 29_level_0',             'Attend.'),
            ( 'Unnamed: 30_level_0',           'Attend./G')],
           )

In [ ]:
advanced_2026.head()
advanced_2026.tail()
advanced_2026.columns
advanced_2026.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 31 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   (Unnamed: 0_level_0, Rk)                    30 non-null     float64
 1   (Unnamed: 1_level_0, Team)                  31 non-null     str
 2   (Unnamed: 2_level_0, Age)                   31 non-null     float64
 3   (Unnamed: 3_level_0, W)                     30 non-null     float64
 4   (Unnamed: 4_level_0, L)                     30 non-null     float64
 5   (Unnamed: 5_level_0, PW)                    31 non-null     int64
 6   (Unnamed: 6_level_0, PL)                    31 non-null     int64
 7   (Unnamed: 7_level_0, MOV)                   31 non-null     float64
 8   (Unnamed: 8_level_0, SOS)                   31 non-null     float64
 9   (Unnamed: 9_level_0, SRS)                   31 non-null     float64
 10  (Unnamed: 10_level_0, ORtg)                 31 non-null     float64
 11  (Unnamed: 11_level_0, DRtg)                 31 non-null     float64
 12  (Unnamed: 12_level_0, NRtg)                 30 non-null     float64
 13  (Unnamed: 13_level_0, Pace)                 31 non-null     float64
 14  (Unnamed: 14_level_0, FTr)                  31 non-null     float64
 15  (Unnamed: 15_level_0, 3PAr)                 31 non-null     float64
 16  (Unnamed: 16_level_0, TS%)                  31 non-null     float64
 17  (Unnamed: 17_level_0, Unnamed: 17_level_1)  0 non-null      float64
 18  (Offense Four Factors, eFG%)                31 non-null     float64
 19  (Offense Four Factors, TOV%)                31 non-null     float64
 20  (Offense Four Factors, ORB%)                31 non-null     float64
 21  (Offense Four Factors, FT/FGA)              31 non-null     float64
 22  (Unnamed: 22_level_0, Unnamed: 22_level_1)  0 non-null      float64
 23  (Defense Four Factors, eFG%)                31 non-null     float64
 24  (Defense Four Factors, TOV%)                31 non-null     float64
 25  (Defense Four Factors, DRB%)                31 non-null     float64
 26  (Defense Four Factors, FT/FGA)              31 non-null     float64
 27  (Unnamed: 27_level_0, Unnamed: 27_level_1)  0 non-null      float64
 28  (Unnamed: 28_level_0, Arena)                30 non-null     str
 29  (Unnamed: 29_level_0, Attend.)              31 non-null     int64
 30  (Unnamed: 30_level_0, Attend./G)            31 non-null     int64
dtypes: float64(25), int64(4), str(2)
memory usage: 7.6 KB

In [ ]:
advanced_2026.columns.tolist()

[('Unnamed: 0_level_0', 'Rk'),
 ('Unnamed: 1_level_0', 'Team'),
 ('Unnamed: 2_level_0', 'Age'),
 ('Unnamed: 3_level_0', 'W'),
 ('Unnamed: 4_level_0', 'L'),
 ('Unnamed: 5_level_0', 'PW'),
 ('Unnamed: 6_level_0', 'PL'),
 ('Unnamed: 7_level_0', 'MOV'),
 ('Unnamed: 8_level_0', 'SOS'),
 ('Unnamed: 9_level_0', 'SRS'),
 ('Unnamed: 10_level_0', 'ORtg'),
 ('Unnamed: 11_level_0', 'DRtg'),
 ('Unnamed: 12_level_0', 'NRtg'),
 ('Unnamed: 13_level_0', 'Pace'),
 ('Unnamed: 14_level_0', 'FTr'),
 ('Unnamed: 15_level_0', '3PAr'),
 ('Unnamed: 16_level_0', 'TS%'),
 ('Unnamed: 17_level_0', 'Unnamed: 17_level_1'),
 ('Offense Four Factors', 'eFG%'),
 ('Offense Four Factors', 'TOV%'),
 ('Offense Four Factors', 'ORB%'),
 ('Offense Four Factors', 'FT/FGA'),
 ('Unnamed: 22_level_0', 'Unnamed: 22_level_1'),
 ('Defense Four Factors', 'eFG%'),
 ('Defense Four Factors', 'TOV%'),
 ('Defense Four Factors', 'DRB%'),
 ('Defense Four Factors', 'FT/FGA'),
 ('Unnamed: 27_level_0', 'Unnamed: 27_level_1'),
 ('Unnamed: 28_level_0', 'Arena'),
 ('Unnamed: 29_level_0', 'Attend.'),
 ('Unnamed: 30_level_0', 'Attend./G')]

In [ ]:
advanced_2026.columns.get_level_values(1)

Index(['Rk', 'Team', 'Age', 'W', 'L', 'PW', 'PL', 'MOV', 'SOS', 'SRS', 'ORtg',
       'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'Unnamed: 17_level_1',
       'eFG%', 'TOV%', 'ORB%', 'FT/FGA', 'Unnamed: 22_level_1', 'eFG%', 'TOV%',
       'DRB%', 'FT/FGA', 'Unnamed: 27_level_1', 'Arena', 'Attend.',
       'Attend./G'],
      dtype='str')

In [ ]:
new_columns = [
    "Rank",
    "Team",
    "Age",
    "W",
    "L",
    "PW",
    "PL",
    "MOV",
    "SOS",
    "SRS",
    "ORtg",
    "DRtg",
    "NRtg",
    "Pace",
    "FTr",
    "3PAr",
    "TS%",
    "separator_1",
    "off_eFG%",
    "off_TOV%",
    "off_ORB%",
    "off_FT/FGA",
    "separator_2",
    "def_eFG%",
    "def_TOV%",
    "def_DRB%",
    "def_FT/FGA",
    "separator_3",
    "Arena",
    "Attend.",
    "Attend./G"
]

print(len(advanced_2026.columns))
print(len(new_columns))

31
31

In [ ]:
advanced_2026.columns = new_columns

len(advanced_2026.columns)

31

In [ ]:
advanced_2026_no_separators = advanced_2026.drop(columns = ["separator_1", "separator_2", "separator_3"])

len(advanced_2026_no_separators.columns)

28

In [ ]:
advanced_2026_no_separators.tail()

,Rank,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,off_TOV%,off_ORB%,off_FT/FGA,def_eFG%,def_TOV%,def_DRB%,def_FT/FGA,Arena,Attend.,Attend./G
26,27.0,Utah Jazz,24.1,22.0,60.0,23,59,-8.43,0.38,-8.05,...,13.2,26.2,0.218,0.578,12.4,72.9,0.227,Delta Center,745626,18186
27,28.0,Sacramento Kings,28.3,22.0,60.0,19,63,-10.00,0.42,-9.58,...,12.6,25.9,0.198,0.572,12.3,73.5,0.216,Golden 1 Center,661735,16140
28,29.0,Brooklyn Nets,23.5,20.0,62.0,18,64,-9.99,0.29,-9.70,...,14.3,23.6,0.212,0.571,13.2,74.0,0.225,Barclays Center,713896,17412
29,30.0,Washington Wizards,23.5,17.0,65.0,16,66,-11.98,0.36,-11.62,...,13.6,24.1,0.180,0.563,11.7,70.2,0.232,Capital One Arena,660376,16107
30,NaN,League Average,26.2,NaN,NaN,41,41,0.00,0.00,0.00,...,12.7,26.0,0.206,0.546,12.7,74.0,0.206,NaN,742347,18111

In [ ]:
advanced_2026_no_avg = advanced_2026_no_separators[advanced_2026_no_separators["Team"] != "League Average"].copy()

advanced_2026_no_avg.head()

,Rank,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,off_TOV%,off_ORB%,off_FT/FGA,def_eFG%,def_TOV%,def_DRB%,def_FT/FGA,Arena,Attend.,Attend./G
0,1.0,Oklahoma City Thunder*,25.2,64.0,18.0,65,17,11.15,-0.11,11.04,...,11.2,22.3,0.213,0.519,14.6,74.4,0.184,Paycom Center,764842,18203
1,2.0,San Antonio Spurs*,25.4,62.0,20.0,60,22,8.30,-0.03,8.28,...,11.8,26.2,0.215,0.522,11.5,77.3,0.180,Frost Bank Center,743129,18703
2,3.0,Detroit Pistons*,26.1,60.0,22.0,60,22,8.16,-0.63,7.53,...,13.0,30.9,0.223,0.517,14.8,74.2,0.251,Little Caesars Arena,806422,19651
3,4.0,Boston Celtics*,26.9,56.0,26.0,59,23,7.70,-0.33,7.37,...,11.2,29.2,0.167,0.523,11.4,75.7,0.189,TD Garden,785396,19156
4,5.0,New York Knicks*,28.1,53.0,29.0,56,26,6.33,-0.28,6.05,...,12.1,29.3,0.188,0.541,13.1,76.7,0.206,Madison Square Garden (IV),792480,19812

In [ ]:
advanced_2026_no_star = advanced_2026_no_avg.copy()

advanced_2026_no_star["Team"] = (advanced_2026_no_star["Team"].str.replace("*", "", regex=False))

advanced_2026_no_star.head()

,Rank,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,off_TOV%,off_ORB%,off_FT/FGA,def_eFG%,def_TOV%,def_DRB%,def_FT/FGA,Arena,Attend.,Attend./G
0,1.0,Oklahoma City Thunder,25.2,64.0,18.0,65,17,11.15,-0.11,11.04,...,11.2,22.3,0.213,0.519,14.6,74.4,0.184,Paycom Center,764842,18203
1,2.0,San Antonio Spurs,25.4,62.0,20.0,60,22,8.30,-0.03,8.28,...,11.8,26.2,0.215,0.522,11.5,77.3,0.180,Frost Bank Center,743129,18703
2,3.0,Detroit Pistons,26.1,60.0,22.0,60,22,8.16,-0.63,7.53,...,13.0,30.9,0.223,0.517,14.8,74.2,0.251,Little Caesars Arena,806422,19651
3,4.0,Boston Celtics,26.9,56.0,26.0,59,23,7.70,-0.33,7.37,...,11.2,29.2,0.167,0.523,11.4,75.7,0.189,TD Garden,785396,19156
4,5.0,New York Knicks,28.1,53.0,29.0,56,26,6.33,-0.28,6.05,...,12.1,29.3,0.188,0.541,13.1,76.7,0.206,Madison Square Garden (IV),792480,19812

In [ ]:
advanced_2026_no_star["season"] = "2025-2026"
advanced_2026_no_star["year"] = 2026

advanced_2026_clean = advanced_2026_no_star.copy()

advanced_2026_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rank        30 non-null     float64
 1   Team        30 non-null     str
 2   Age         30 non-null     float64
 3   W           30 non-null     float64
 4   L           30 non-null     float64
 5   PW          30 non-null     int64
 6   PL          30 non-null     int64
 7   MOV         30 non-null     float64
 8   SOS         30 non-null     float64
 9   SRS         30 non-null     float64
 10  ORtg        30 non-null     float64
 11  DRtg        30 non-null     float64
 12  NRtg        30 non-null     float64
 13  Pace        30 non-null     float64
 14  FTr         30 non-null     float64
 15  3PAr        30 non-null     float64
 16  TS%         30 non-null     float64
 17  off_eFG%    30 non-null     float64
 18  off_TOV%    30 non-null     float64
 19  off_ORB%    30 non-null     float64
 20  off_FT/FGA  30 non-null     float64
 21  def_eFG%    30 non-null     float64
 22  def_TOV%    30 non-null     float64
 23  def_DRB%    30 non-null     float64
 24  def_FT/FGA  30 non-null     float64
 25  Arena       30 non-null     str
 26  Attend.     30 non-null     int64
 27  Attend./G   30 non-null     int64
 28  season      30 non-null     str
 29  year        30 non-null     int64
dtypes: float64(22), int64(5), str(3)
memory usage: 7.2 KB

In [ ]:
advanced_2026_clean["Rank"] = advanced_2026_clean["Rank"].astype(int)
advanced_2026_clean["W"] = advanced_2026_clean["W"].astype(int)
advanced_2026_clean["L"] = advanced_2026_clean["L"].astype(int)
advanced_2026_clean["PW"] = advanced_2026_clean["PW"].astype(int)
advanced_2026_clean["PL"] = advanced_2026_clean["PL"].astype(int)

advanced_2026_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rank        30 non-null     int64
 1   Team        30 non-null     str
 2   Age         30 non-null     float64
 3   W           30 non-null     int64
 4   L           30 non-null     int64
 5   PW          30 non-null     int64
 6   PL          30 non-null     int64
 7   MOV         30 non-null     float64
 8   SOS         30 non-null     float64
 9   SRS         30 non-null     float64
 10  ORtg        30 non-null     float64
 11  DRtg        30 non-null     float64
 12  NRtg        30 non-null     float64
 13  Pace        30 non-null     float64
 14  FTr         30 non-null     float64
 15  3PAr        30 non-null     float64
 16  TS%         30 non-null     float64
 17  off_eFG%    30 non-null     float64
 18  off_TOV%    30 non-null     float64
 19  off_ORB%    30 non-null     float64
 20  off_FT/FGA  30 non-null     float64
 21  def_eFG%    30 non-null     float64
 22  def_TOV%    30 non-null     float64
 23  def_DRB%    30 non-null     float64
 24  def_FT/FGA  30 non-null     float64
 25  Arena       30 non-null     str
 26  Attend.     30 non-null     int64
 27  Attend./G   30 non-null     int64
 28  season      30 non-null     str
 29  year        30 non-null     int64
dtypes: float64(19), int64(8), str(3)
memory usage: 7.2 KB

## S02 Production Pipeline

In [ ]:
# Creating the final pipeline and automating away the code... #

import pandas as pd
import ssl
import certifi
import urllib.request
import io

def get_stats(year):

    url = f"https://www.basketball-reference.com/leagues/NBA_{year}.html"

    context = ssl.create_default_context(cafile=certifi.where())

    with urllib.request.urlopen(url, context=context) as response:
        html = response.read()

    tables = pd.read_html(io.BytesIO(html))

    if year <= 2015:
        advanced_stats = tables[8].copy()
    else:
        advanced_stats = tables[10].copy()

    return advanced_stats


def cleaned_stats(df, year):
    df = df.copy()

    new_columns = [
        "Rank",
        "Team",
        "Age",
        "W",
        "L",
        "PW",
        "PL",
        "MOV",
        "SOS",
        "SRS",
        "ORtg",
        "DRtg",
        "NRtg",
        "Pace",
        "FTr",
        "3PAr",
        "TS%",
        "separator_1",
        "off_eFG%",
        "off_TOV%",
        "off_ORB%",
        "off_FT/FGA",
        "separator_2",
        "def_eFG%",
        "def_TOV%",
        "def_DRB%",
        "def_FT/FGA",
        "separator_3",
        "Arena",
        "Attend.",
        "Attend./G"
    ]

    df.columns = new_columns

    df = df.drop(columns=["separator_1", "separator_2", "separator_3"]).copy()

    df = df[df["Team"] != "League Average"].copy()

    df["Team"] = (df["Team"].str.replace("*", "", regex=False))
    df["season"] = f"{year - 1}-{year}"
    df["year"] = year

    df["Rank"] = df["Rank"].astype(int)
    df["W"] = df["W"].astype(int)
    df["L"] = df["L"].astype(int)
    df["PW"] = df["PW"].astype(int)
    df["PL"] = df["PL"].astype(int)

    return df


import time

historical_advanced_stats = []

for year in range(2001, 2027):

    find_table = get_stats(year)

    cleaned_table = cleaned_stats(find_table, year)

    historical_advanced_stats.append(cleaned_table)


time.sleep(10)


len(historical_advanced_stats)

all_advanced_stats = pd.concat(historical_advanced_stats, ignore_index=True)


### SANITY CHECK FOR AFTER THE FUNCTIONS

# Basic structure
print(all_advanced_stats.shape)
all_advanced_stats.info()

# Historical coverage
print(all_advanced_stats["season"].nunique())
print(all_advanced_stats["year"].min())
print(all_advanced_stats["year"].max())

# Teams per season
print(
    all_advanced_stats.groupby("season")["Team"].nunique()
)

# Duplicate team-seasons
print(
    all_advanced_stats.duplicated(
        subset=["Team", "season"]
    ).sum()
)

# Missing values
print(
    all_advanced_stats.isna().sum()
)

# Make sure cleaning worked
print(
    (all_advanced_stats["Team"] == "League Average").sum()
)

print(
    all_advanced_stats["Team"].str.contains(
        "*",
        regex=False
    ).sum()
)

HTTPError: HTTP Error 429: Too Many Requests

In [ ]:
import os

os.makedirs(
    "../data/staging/advanced_stats",
    exist_ok=True
)

all_advanced_stats.to_csv(
    "../data/staging/advanced_stats/s02_advanced_stats.csv",
    index=False
)

check_s02 = pd.read_csv(
    "../data/staging/advanced_stats/s02_advanced_stats.csv"
)

print(check_s02.shape)
check_s02.info()