Building the s07 pipeline where we capture data that allows us to get salary information on the books by player x team per season...

In [9]:
import pandas as pd

url = "https://www.espn.com/nba/salaries/_/year/2026/seasontype/1"

salary_test = pd.read_html(url)

len(salary_test)

salaries = salary_test[0]

salaries.head()

    0                 1                      2            3
0  RK              NAME                   TEAM       SALARY
1   1  Stephen Curry, G  Golden State Warriors  $59,606,817
2   2    Joel Embiid, C     Philadelphia 76ers  $55,224,526
3   3   Nikola Jokic, C         Denver Nuggets  $55,224,526
4   4   Kevin Durant, F        Houston Rockets  $54,708,609

In [10]:
url2 = "https://www.espn.com/nba/salaries/_/year/2026/page/2/seasontype/1"

salary_test_2 = pd.read_html(url)

len(salary_test_2)

salaries_2 = salary_test_2[0]

salaries_2.head()

    0                 1                      2            3
0  RK              NAME                   TEAM       SALARY
1   1  Stephen Curry, G  Golden State Warriors  $59,606,817
2   2    Joel Embiid, C     Philadelphia 76ers  $55,224,526
3   3   Nikola Jokic, C         Denver Nuggets  $55,224,526
4   4   Kevin Durant, F        Houston Rockets  $54,708,609