### Getting end of season awards + the defensive team selections for first and second team from html tables in Basketball Reference

In [37]:
import pandas as pd
import requests
import certifi
import os

from io import StringIO

awards_url = "https://www.basketball-reference.com/awards/awards_2026.html"

response = requests.get(
    awards_url,
    verify=certifi.where(),
    timeout=20
)

response.raise_for_status()

awards_tables = pd.read_html(
    StringIO(response.content.decode("utf-8"))
)

len(awards_tables)

5

In [38]:
print(f"Number of tables: {len(awards_tables)}")

for i, df in enumerate(awards_tables):
    print(i, df.shape, df.columns.tolist())

Number of tables: 5
0 (8, 20) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
1 (5, 20) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
2 (31, 23) [('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Pos'), ('Unnamed: 2_level_0', 'Player'), ('Unnamed: 3_level_0', 'Age'), ('Unnamed: 4_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Voting', '1st Tm'), ('Voting', '2nd Tm'), ('Voting', '3rd Tm'), ('Unnamed: 11_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
3 (27, 23) [('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Pos'), ('Unnamed: 2_level_0', 'Player'), ('Unnamed: 3_level_0', 'Age'), ('Unnamed: 4_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48'), ('Advanced', 'DWS'), ('Advanced', 'DBPM'), ('Advanced', 'DRtg')]
4 (21, 21) [('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Voting', '1st Tm'), ('Voting', '2nd Tm'), ('Unnamed: 9_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]

In [39]:
from bs4 import BeautifulSoup, Comment

html = response.content.decode("utf-8")
soup = BeautifulSoup(html, "html.parser")

visible_tables = soup.find_all("table")
comments = soup.find_all(string=lambda text: isinstance(text, Comment))

commented_tables = sum(
    len(BeautifulSoup(comment, "html.parser").find_all("table"))
    for comment in comments
)

print("Visible HTML tables:", len(visible_tables))
print("Tables inside comments:", commented_tables)
print("Pandas DataFrames:", len(awards_tables))

Visible HTML tables: 5
Tables inside comments: 5
Pandas DataFrames: 5

In [40]:
commented_awards = []

for comment in comments:
    tables = BeautifulSoup(comment, "html.parser").find_all("table")

    for table in tables:
        df = pd.read_html(StringIO(str(table)))[0]
        commented_awards.append(df)

In [41]:
all_awards_tables = awards_tables + commented_awards

print(len(all_awards_tables))

10

In [42]:
for i, df in enumerate(all_awards_tables):
    print(i, df.shape, df.columns.tolist())

0 (8, 20) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
1 (5, 20) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
2 (31, 23) [('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Pos'), ('Unnamed: 2_level_0', 'Player'), ('Unnamed: 3_level_0', 'Age'), ('Unnamed: 4_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Voting', '1st Tm'), ('Voting', '2nd Tm'), ('Voting', '3rd Tm'), ('Unnamed: 11_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
3 (27, 23) [('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Pos'), ('Unnamed: 2_level_0', 'Player'), ('Unnamed: 3_level_0', 'Age'), ('Unnamed: 4_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48'), ('Advanced', 'DWS'), ('Advanced', 'DBPM'), ('Advanced', 'DRtg')]
4 (21, 21) [('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Voting', '1st Tm'), ('Voting', '2nd Tm'), ('Unnamed: 9_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
5 (13, 23) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48'), ('Advanced', 'DWS'), ('Advanced', 'DBPM'), ('Advanced', 'DRtg')]
6 (12, 20) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
7 (14, 20) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
8 (10, 20) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]
9 (12, 11) [('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Coach'), ('Unnamed: 2_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 7_level_0', 'G'), ('Unnamed: 8_level_0', 'W'), ('Unnamed: 9_level_0', 'L'), ('Unnamed: 10_level_0', 'W/L%')]

In [43]:
all_awards_tables[2].head(15)

   Unnamed: 0_level_0 Unnamed: 1_level_0       Unnamed: 2_level_0  \
                 # Tm                Pos                   Player
0                 NaN                NaN                      NaN
1                  1T                  G  Shai Gilgeous-Alexander
2                  1T                  C             Nikola Jokić
3                  1T                  C        Victor Wembanyama
4                  1T                  G              Luka Dončić
5                  1T                  G          Cade Cunningham
6                 NaN                NaN                      NaN
7                  2T                  F             Jaylen Brown
8                  2T                  F            Kawhi Leonard
9                  2T                  G         Donovan Mitchell
10                 2T                  F             Kevin Durant
11                 2T                  G            Jalen Brunson
12                NaN                NaN                      NaN
13                 3T                  G             Tyrese Maxey
14                 3T                  G             Jamal Murray

   Unnamed: 3_level_0 Unnamed: 4_level_0  Voting                               \
                  Age                 Tm Pts Won Pts Max  Share 1st Tm 2nd Tm
0                 NaN                NaN     NaN     NaN    NaN    NaN    NaN
1                27.0                OKC   500.0   500.0  1.000  100.0    0.0
2                30.0                DEN   500.0   500.0  1.000  100.0    0.0
3                22.0                SAS   498.0   500.0  0.996   99.0    1.0
4                26.0                LAL   482.0   500.0  0.964   91.0    9.0
5                24.0                DET   414.0   500.0  0.828   60.0   38.0
6                 NaN                NaN     NaN     NaN    NaN    NaN    NaN
7                29.0                BOS   384.0   500.0  0.768   44.0   54.0
8                34.0                LAC   277.0   500.0  0.554    4.0   81.0
9                29.0                CLE   276.0   500.0  0.552    2.0   85.0
10               37.0                HOU   241.0   500.0  0.482    0.0   72.0
11               29.0                NYK   197.0   500.0  0.394    0.0   49.0
12                NaN                NaN     NaN     NaN    NaN    NaN    NaN
13               25.0                PHI   168.0   500.0  0.336    0.0   36.0
14               28.0                DEN   149.0   500.0  0.298    0.0   27.0

    ... Per Game                       Shooting               Advanced
    ...      PTS   TRB   AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
0   ...      NaN   NaN   NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
1   ...     31.1   4.3   6.6  1.4  0.8    0.553  0.386  0.879     15.2  0.323
2   ...     27.7  12.9  10.7  1.4  0.8    0.569  0.380  0.831     14.9  0.316
3   ...     25.0  11.5   3.1  1.0  3.1    0.512  0.349  0.827     10.0  0.257
4   ...     33.5   7.7   8.3  1.6  0.5    0.476  0.366  0.780      9.5  0.199
5   ...     23.9   5.5   9.9  1.4  0.8    0.461  0.342  0.812      7.9  0.174
6   ...      NaN   NaN   NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
7   ...     28.7   6.9   5.1  1.0  0.4    0.477  0.347  0.795      6.9  0.135
8   ...     27.9   6.4   3.6  1.9  0.4    0.505  0.387  0.892      9.2  0.212
9   ...     27.9   4.5   5.7  1.5  0.3    0.483  0.364  0.865      8.2  0.169
10  ...     26.0   5.5   4.8  0.8  0.9    0.520  0.413  0.874     10.7  0.180
11  ...     26.0   3.3   6.8  0.8  0.1    0.467  0.369  0.841      8.8  0.163
12  ...      NaN   NaN   NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
13  ...     28.3   4.1   6.6  1.9  0.8    0.462  0.367  0.892      8.7  0.156
14  ...     25.4   4.4   7.1  0.9  0.4    0.483  0.435  0.887      9.5  0.173

[15 rows x 23 columns]

In [44]:
# Collect the five visible HTML tables
all_html_tables = soup.find_all("table")

# Add the five tables embedded in HTML comments
for comment in comments:
    comment_soup = BeautifulSoup(comment, "html.parser")
    all_html_tables.extend(comment_soup.find_all("table"))

# Inspect each table's HTML ID
for i, table in enumerate(all_html_tables):
    print(i, table.get("id"))

0 mvp
1 roy
2 leading_all_nba
3 leading_all_defense
4 leading_all_rookie
5 dpoy
6 smoy
7 mip
8 clutch_poy
9 coy

In [45]:
import pandas as pd
import requests
import certifi

from bs4 import BeautifulSoup, Comment
from io import StringIO

# 1. Select the season (change this URL each time)
url = "https://www.basketball-reference.com/awards/awards_2026.html"

# 2. Download the webpage
response = requests.get(
    url,
    verify=certifi.where(),
    timeout=20
)

response.raise_for_status()

# 3. Decode HTML using UTF-8
html = response.content.decode("utf-8")

# 4. Parse the webpage with BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# 5. Find visible HTML tables
all_html_tables = soup.find_all("table")

# 6. Find tables hidden inside HTML comments
comments = soup.find_all(
    string=lambda text: isinstance(text, Comment)
)

for comment in comments:
    comment_soup = BeautifulSoup(comment, "html.parser")
    all_html_tables.extend(comment_soup.find_all("table"))

# 7. Print table IDs to identify awards
for i, table in enumerate(all_html_tables):
    print(i, table.get("id"))

# 8. Convert all HTML tables into pandas DataFrames
awards_tables = []

for table in all_html_tables:
    df = pd.read_html(StringIO(str(table)))[0]
    awards_tables.append(df)

print(f"\nTotal DataFrames extracted: {len(awards_tables)}")

0 mvp
1 roy
2 leading_all_nba
3 leading_all_defense
4 leading_all_rookie
5 dpoy
6 smoy
7 mip
8 clutch_poy
9 coy

Total DataFrames extracted: 10

In [46]:
import pandas as pd
import requests
import certifi

from bs4 import BeautifulSoup, Comment
from io import StringIO

# 1. Select the season (change this URL each time)
url = "https://www.basketball-reference.com/awards/awards_2021.html"

# 2. Download the webpage
response = requests.get(
    url,
    verify=certifi.where(),
    timeout=20
)

response.raise_for_status()

# 3. Decode HTML using UTF-8
html = response.content.decode("utf-8")

# 4. Parse the webpage with BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# 5. Find visible HTML tables
all_html_tables = soup.find_all("table")

# 6. Find tables hidden inside HTML comments
comments = soup.find_all(
    string=lambda text: isinstance(text, Comment)
)

for comment in comments:
    comment_soup = BeautifulSoup(comment, "html.parser")
    all_html_tables.extend(comment_soup.find_all("table"))

# 7. Print table IDs to identify awards
for i, table in enumerate(all_html_tables):
    print(i, table.get("id"))

# 8. Convert all HTML tables into pandas DataFrames
awards_tables = []

for table in all_html_tables:
    df = pd.read_html(StringIO(str(table)))[0]
    awards_tables.append(df)

print(f"\nTotal DataFrames extracted: {len(awards_tables)}")

0 mvp
1 roy
2 leading_all_nba
3 leading_all_defense
4 leading_all_rookie
5 dpoy
6 smoy
7 mip
8 coy

Total DataFrames extracted: 9

In [47]:
import pandas as pd
import requests
import certifi

from bs4 import BeautifulSoup, Comment
from io import StringIO

# 1. Select the season (change this URL each time)
url = "https://www.basketball-reference.com/awards/awards_2018.html"

# 2. Download the webpage
response = requests.get(
    url,
    verify=certifi.where(),
    timeout=20
)

response.raise_for_status()

# 3. Decode HTML using UTF-8
html = response.content.decode("utf-8")

# 4. Parse the webpage with BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# 5. Find visible HTML tables
all_html_tables = soup.find_all("table")

# 6. Find tables hidden inside HTML comments
comments = soup.find_all(
    string=lambda text: isinstance(text, Comment)
)

for comment in comments:
    comment_soup = BeautifulSoup(comment, "html.parser")
    all_html_tables.extend(comment_soup.find_all("table"))

# 7. Print table IDs to identify awards
for i, table in enumerate(all_html_tables):
    print(i, table.get("id"))

# 8. Convert all HTML tables into pandas DataFrames
awards_tables = []

for table in all_html_tables:
    df = pd.read_html(StringIO(str(table)))[0]
    awards_tables.append(df)

print(f"\nTotal DataFrames extracted: {len(awards_tables)}")

0 mvp
1 roy
2 leading_all_nba
3 leading_all_defense
4 leading_all_rookie
5 dpoy
6 smoy
7 mip
8 coy

Total DataFrames extracted: 9

In [48]:
import pandas as pd
import requests
import certifi

from bs4 import BeautifulSoup, Comment
from io import StringIO

# 1. Select the season (change this URL each time)
url = "https://www.basketball-reference.com/awards/awards_2012.html"

# 2. Download the webpage
response = requests.get(
    url,
    verify=certifi.where(),
    timeout=20
)

response.raise_for_status()

# 3. Decode HTML using UTF-8
html = response.content.decode("utf-8")

# 4. Parse the webpage with BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# 5. Find visible HTML tables
all_html_tables = soup.find_all("table")

# 6. Find tables hidden inside HTML comments
comments = soup.find_all(
    string=lambda text: isinstance(text, Comment)
)

for comment in comments:
    comment_soup = BeautifulSoup(comment, "html.parser")
    all_html_tables.extend(comment_soup.find_all("table"))

# 7. Print table IDs to identify awards
for i, table in enumerate(all_html_tables):
    print(i, table.get("id"))

# 8. Convert all HTML tables into pandas DataFrames
awards_tables = []

for table in all_html_tables:
    df = pd.read_html(StringIO(str(table)))[0]
    awards_tables.append(df)

print(f"\nTotal DataFrames extracted: {len(awards_tables)}")

0 mvp
1 roy
2 leading_all_nba
3 leading_all_defense
4 leading_all_rookie
5 dpoy
6 smoy
7 mip
8 coy

Total DataFrames extracted: 9

In [49]:
import pandas as pd
import requests
import certifi

from bs4 import BeautifulSoup, Comment
from io import StringIO

# 1. Select the season (change this URL each time)
url = "https://www.basketball-reference.com/awards/awards_2008.html"

# 2. Download the webpage
response = requests.get(
    url,
    verify=certifi.where(),
    timeout=20
)

response.raise_for_status()

# 3. Decode HTML using UTF-8
html = response.content.decode("utf-8")

# 4. Parse the webpage with BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# 5. Find visible HTML tables
all_html_tables = soup.find_all("table")

# 6. Find tables hidden inside HTML comments
comments = soup.find_all(
    string=lambda text: isinstance(text, Comment)
)

for comment in comments:
    comment_soup = BeautifulSoup(comment, "html.parser")
    all_html_tables.extend(comment_soup.find_all("table"))

# 7. Print table IDs to identify awards
for i, table in enumerate(all_html_tables):
    print(i, table.get("id"))

# 8. Convert all HTML tables into pandas DataFrames
awards_tables = []

for table in all_html_tables:
    df = pd.read_html(StringIO(str(table)))[0]
    awards_tables.append(df)

print(f"\nTotal DataFrames extracted: {len(awards_tables)}")

0 mvp
1 roy
2 leading_all_nba
3 leading_all_defense
4 leading_all_rookie
5 dpoy
6 smoy
7 mip
8 coy

Total DataFrames extracted: 9

In [53]:
import pandas as pd
import requests
import certifi

from bs4 import BeautifulSoup, Comment
from io import StringIO

# 1. Select the season (change this URL each time)
url = "https://www.basketball-reference.com/awards/awards_2001.html"

# 2. Download the webpage
response = requests.get(
    url,
    verify=certifi.where(),
    timeout=20
)

response.raise_for_status()

# 3. Decode HTML using UTF-8
html = response.content.decode("utf-8")

# 4. Parse the webpage with BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# 5. Find visible HTML tables
all_html_tables = soup.find_all("table")

# 6. Find tables hidden inside HTML comments
comments = soup.find_all(
    string=lambda text: isinstance(text, Comment)
)

for comment in comments:
    comment_soup = BeautifulSoup(comment, "html.parser")
    all_html_tables.extend(comment_soup.find_all("table"))

# 7. Print table IDs to identify awards
for i, table in enumerate(all_html_tables):
    print(i, table.get("id"))

# 8. Convert all HTML tables into pandas DataFrames
awards_tables = []

for table in all_html_tables:
    df = pd.read_html(StringIO(str(table)))[0]
    awards_tables.append(df)

print(f"\nTotal DataFrames extracted: {len(awards_tables)}")

0 mvp
1 roy
2 leading_all_nba
3 leading_all_defense
4 leading_all_rookie
5 dpoy
6 smoy
7 mip
8 coy

Total DataFrames extracted: 9

In [54]:
# Identify each table by its HTML ID

mvp_html = next(table for table in all_html_tables if table.get("id") == "mvp")

roy_html = next(table for table in all_html_tables if table.get("id") == "roy")

dpoy_html = next(table for table in all_html_tables if table.get("id") == "dpoy")

defense_html = next(table for table in all_html_tables if table.get("id") == "leading_all_defense")

rookie_html = next(table for table in all_html_tables if table.get("id") == "leading_all_rookie")

# Convert each HTML table into a pandas DataFrame

mvp_df = pd.read_html(StringIO(str(mvp_html)))[0]

roy_df = pd.read_html(StringIO(str(roy_html)))[0]

dpoy_df = pd.read_html(StringIO(str(dpoy_html)))[0]

defense_df = pd.read_html(StringIO(str(defense_html)))[0]

rookie_df = pd.read_html(StringIO(str(rookie_html)))[0]

In [57]:
mvp_df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Rank             Player                Age                 Tm
0                  1      Allen Iverson                 25                PHI
1                  2         Tim Duncan                 24                SAS
2                  3   Shaquille O'Neal                 28                LAL
3                  4       Chris Webber                 27                SAC
4                  5      Kevin Garnett                 24                MIN

  Voting                        Unnamed: 8_level_0 Per Game                   \
   First Pts Won Pts Max  Share                  G       MP   PTS   TRB  AST
0     93    1121    1240  0.904                 71     42.0  31.1   3.8  4.6
1     18     706    1240  0.569                 82     38.7  22.2  12.2  3.0
2      7     578    1240  0.466                 74     39.5  28.7  12.7  3.7
3      5     521    1240  0.420                 70     40.5  27.1  11.1  4.2
4      1     151    1240  0.122                 81     39.5  22.0  11.4  5.0

            Shooting               Advanced
   STL  BLK      FG%    3P%    FT%       WS  WS/48
0  2.5  0.3    0.420  0.320  0.814     11.8  0.190
1  0.9  2.3    0.499  0.259  0.618     13.2  0.200
2  0.6  2.8    0.572  0.000  0.513     14.9  0.245
3  1.3  1.7    0.481  0.071  0.703     11.0  0.186
4  1.4  1.8    0.477  0.288  0.764     11.8  0.176

In [59]:
mvp_df.columns.tolist()

[('Unnamed: 0_level_0', 'Rank'),
 ('Unnamed: 1_level_0', 'Player'),
 ('Unnamed: 2_level_0', 'Age'),
 ('Unnamed: 3_level_0', 'Tm'),
 ('Voting', 'First'),
 ('Voting', 'Pts Won'),
 ('Voting', 'Pts Max'),
 ('Voting', 'Share'),
 ('Unnamed: 8_level_0', 'G'),
 ('Per Game', 'MP'),
 ('Per Game', 'PTS'),
 ('Per Game', 'TRB'),
 ('Per Game', 'AST'),
 ('Per Game', 'STL'),
 ('Per Game', 'BLK'),
 ('Shooting', 'FG%'),
 ('Shooting', '3P%'),
 ('Shooting', 'FT%'),
 ('Advanced', 'WS'),
 ('Advanced', 'WS/48')]

In [60]:
mvp_df.columns = mvp_df.columns.get_level_values(-1)

mvp_df.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Allen Iverson,25,PHI,93,1121,1240,0.904,71,42.0,31.1,3.8,4.6,2.5,0.3,0.420,0.320,0.814,11.8,0.190
1,2,Tim Duncan,24,SAS,18,706,1240,0.569,82,38.7,22.2,12.2,3.0,0.9,2.3,0.499,0.259,0.618,13.2,0.200
2,3,Shaquille O'Neal,28,LAL,7,578,1240,0.466,74,39.5,28.7,12.7,3.7,0.6,2.8,0.572,0.000,0.513,14.9,0.245
3,4,Chris Webber,27,SAC,5,521,1240,0.420,70,40.5,27.1,11.1,4.2,1.3,1.7,0.481,0.071,0.703,11.0,0.186
4,5,Kevin Garnett,24,MIN,1,151,1240,0.122,81,39.5,22.0,11.4,5.0,1.4,1.8,0.477,0.288,0.764,11.8,0.176

In [61]:
mvp_df_final = mvp_df[["Rank", "Player", "Age", "Tm", "First", "Pts Won", "Pts Max", "Share"]].copy()

mvp_df_final.head()

  Rank            Player  Age   Tm  First  Pts Won  Pts Max  Share
0    1     Allen Iverson   25  PHI     93     1121     1240  0.904
1    2        Tim Duncan   24  SAS     18      706     1240  0.569
2    3  Shaquille O'Neal   28  LAL      7      578     1240  0.466
3    4      Chris Webber   27  SAC      5      521     1240  0.420
4    5     Kevin Garnett   24  MIN      1      151     1240  0.122

In [ ]:
mvp_final = mvp_df_final.rename(columns={
    "Rank": "voting_rank",
    "Player": "player_name",
    "Age": "age",
    "Tm": "team",
    "First": "first_place_votes",
    "Pts Won": "points_won",
    "Pts Max": "points_max",
    "Share": "vote_share"
}).copy()

mvp_final["season"] = "2000-2001"
mvp_final["season_end_year"] = 2001

mvp_final["award_winner"] = mvp_final["voting_rank"] == 1

In [72]:
mvp_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   voting_rank        17 non-null     str
 1   player_name        17 non-null     str
 2   age                17 non-null     int64
 3   team               17 non-null     str
 4   first_place_votes  17 non-null     int64
 5   points_won         17 non-null     int64
 6   points_max         17 non-null     int64
 7   vote_share         17 non-null     float64
 8   season             17 non-null     str
 9   season_end_year    17 non-null     int64
 10  award_winner       17 non-null     bool
dtypes: bool(1), float64(1), int64(5), str(4)
memory usage: 1.5 KB

In [73]:
mvp_final["voting_rank"] = (
    mvp_final["voting_rank"]
    .str.replace("T", "", regex=False)
    .astype(int)
)

In [74]:
mvp_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   voting_rank        17 non-null     int64
 1   player_name        17 non-null     str
 2   age                17 non-null     int64
 3   team               17 non-null     str
 4   first_place_votes  17 non-null     int64
 5   points_won         17 non-null     int64
 6   points_max         17 non-null     int64
 7   vote_share         17 non-null     float64
 8   season             17 non-null     str
 9   season_end_year    17 non-null     int64
 10  award_winner       17 non-null     bool
dtypes: bool(1), float64(1), int64(6), str(3)
memory usage: 1.5 KB

In [75]:
mvp_final.head()

,voting_rank,player_name,age,team,first_place_votes,points_won,points_max,vote_share,season,season_end_year,award_winner
0,1,Allen Iverson,25,PHI,93,1121,1240,0.904,2000-01,2001,False
1,2,Tim Duncan,24,SAS,18,706,1240,0.569,2000-01,2001,False
2,3,Shaquille O'Neal,28,LAL,7,578,1240,0.466,2000-01,2001,False
3,4,Chris Webber,27,SAC,5,521,1240,0.420,2000-01,2001,False
4,5,Kevin Garnett,24,MIN,1,151,1240,0.122,2000-01,2001,False

In [76]:

mvp_final["award_winner"] = mvp_final["voting_rank"] == 1

In [77]:
mvp_final.head()

,voting_rank,player_name,age,team,first_place_votes,points_won,points_max,vote_share,season,season_end_year,award_winner
0,1,Allen Iverson,25,PHI,93,1121,1240,0.904,2000-01,2001,True
1,2,Tim Duncan,24,SAS,18,706,1240,0.569,2000-01,2001,False
2,3,Shaquille O'Neal,28,LAL,7,578,1240,0.466,2000-01,2001,False
3,4,Chris Webber,27,SAC,5,521,1240,0.420,2000-01,2001,False
4,5,Kevin Garnett,24,MIN,1,151,1240,0.122,2000-01,2001,False

In [78]:
roy_df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Rank             Player                Age                 Tm
0                  1        Mike Miller                 20                ORL
1                  2      Kenyon Martin                 23                NJN
2                  3       Marc Jackson                 26                GSW
3                 4T       Darius Miles                 19                LAC
4                 4T    Morris Peterson                 23                TOR

  Voting                        Unnamed: 8_level_0 Per Game                  \
   First Pts Won Pts Max  Share                  G       MP   PTS  TRB  AST
0     75      75     124  0.605                 82     29.1  11.9  4.0  1.7
1     36      36     124  0.290                 68     33.4  12.0  7.4  1.9
2      7       7     124  0.056                 48     29.4  13.2  7.5  1.2
3      3       3     124  0.024                 81     26.3   9.4  5.9  1.2
4      3       3     124  0.024                 80     22.6   9.3  3.2  1.3

            Shooting               Advanced
   STL  BLK      FG%    3P%    FT%       WS  WS/48
0  0.6  0.2    0.436  0.407  0.711      5.3  0.106
1  1.1  1.7    0.445  0.091  0.630      2.1  0.044
2  0.7  0.6    0.467  0.217  0.802      2.6  0.089
3  0.6  1.5    0.505  0.053  0.521      3.0  0.068
4  0.8  0.3    0.431  0.382  0.717      3.6  0.096

In [81]:
roy_df.columns = roy_df.columns.get_level_values(-1)

In [82]:
roy_df.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Mike Miller,20,ORL,75,75,124,0.605,82,29.1,11.9,4.0,1.7,0.6,0.2,0.436,0.407,0.711,5.3,0.106
1,2,Kenyon Martin,23,NJN,36,36,124,0.290,68,33.4,12.0,7.4,1.9,1.1,1.7,0.445,0.091,0.630,2.1,0.044
2,3,Marc Jackson,26,GSW,7,7,124,0.056,48,29.4,13.2,7.5,1.2,0.7,0.6,0.467,0.217,0.802,2.6,0.089
3,4T,Darius Miles,19,LAC,3,3,124,0.024,81,26.3,9.4,5.9,1.2,0.6,1.5,0.505,0.053,0.521,3.0,0.068
4,4T,Morris Peterson,23,TOR,3,3,124,0.024,80,22.6,9.3,3.2,1.3,0.8,0.3,0.431,0.382,0.717,3.6,0.096

In [85]:
roy_df_final_cols = roy_df[["Rank", "Player", "Age", "Tm", "First", "Pts Won", "Pts Max", "Share"]].copy()

roy_df_final_cols.head()

  Rank           Player  Age   Tm  First  Pts Won  Pts Max  Share
0    1      Mike Miller   20  ORL     75       75      124  0.605
1    2    Kenyon Martin   23  NJN     36       36      124  0.290
2    3     Marc Jackson   26  GSW      7        7      124  0.056
3   4T     Darius Miles   19  LAC      3        3      124  0.024
4   4T  Morris Peterson   23  TOR      3        3      124  0.024

In [86]:
roy_final = roy_df_final_cols.rename(columns={
    "Rank": "voting_rank",
    "Player": "player_name",
    "Age": "age",
    "Tm": "team",
    "First": "first_place_votes",
    "Pts Won": "points_won",
    "Pts Max": "points_max",
    "Share": "vote_share"
}).copy()

roy_final["voting_rank"] = roy_final["voting_rank"].astype(str).str.replace("T", "", regex=False).astype(int)

roy_final["season"] = "2000-2001"
roy_final["year"] = 2001

roy_final["award_winner"] = roy_final["voting_rank"] == 1

roy_final.head()

,voting_rank,player_name,age,team,first_place_votes,points_won,points_max,vote_share,season,year,award_winner
0,1,Mike Miller,20,ORL,75,75,124,0.605,2000-2001,2001,True
1,2,Kenyon Martin,23,NJN,36,36,124,0.290,2000-2001,2001,False
2,3,Marc Jackson,26,GSW,7,7,124,0.056,2000-2001,2001,False
3,4,Darius Miles,19,LAC,3,3,124,0.024,2000-2001,2001,False
4,4,Morris Peterson,23,TOR,3,3,124,0.024,2000-2001,2001,False

In [87]:
roy_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   voting_rank        5 non-null      int64
 1   player_name        5 non-null      str
 2   age                5 non-null      int64
 3   team               5 non-null      str
 4   first_place_votes  5 non-null      int64
 5   points_won         5 non-null      int64
 6   points_max         5 non-null      int64
 7   vote_share         5 non-null      float64
 8   season             5 non-null      str
 9   year               5 non-null      int64
 10  award_winner       5 non-null      bool
dtypes: bool(1), float64(1), int64(6), str(3)
memory usage: 537.0 bytes

In [89]:
dpoy_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   (Unnamed: 0_level_0, Rank)    14 non-null     str
 1   (Unnamed: 1_level_0, Player)  14 non-null     str
 2   (Unnamed: 2_level_0, Age)     14 non-null     int64
 3   (Unnamed: 3_level_0, Tm)      14 non-null     str
 4   (Voting, First)               14 non-null     int64
 5   (Voting, Pts Won)             14 non-null     int64
 6   (Voting, Pts Max)             14 non-null     int64
 7   (Voting, Share)               14 non-null     float64
 8   (Unnamed: 8_level_0, G)       14 non-null     int64
 9   (Per Game, MP)                14 non-null     float64
 10  (Per Game, PTS)               14 non-null     float64
 11  (Per Game, TRB)               14 non-null     float64
 12  (Per Game, AST)               14 non-null     float64
 13  (Per Game, STL)               14 non-null     float64
 14  (Per Game, BLK)               14 non-null     float64
 15  (Shooting, FG%)               14 non-null     float64
 16  (Shooting, 3P%)               11 non-null     float64
 17  (Shooting, FT%)               14 non-null     float64
 18  (Advanced, WS)                14 non-null     float64
 19  (Advanced, WS/48)             14 non-null     float64
 20  (Advanced, DWS)               14 non-null     float64
 21  (Advanced, DBPM)              14 non-null     float64
 22  (Advanced, DRtg)              14 non-null     int64
dtypes: float64(14), int64(6), str(3)
memory usage: 2.6 KB

In [90]:
dpoy_df.columns = dpoy_df.columns.get_level_values(-1)

dpoy_df_final_cols = dpoy_df[["Rank", "Player", "Age", "Tm", "First", "Pts Won", "Pts Max", "Share"]]

dpoy_df_final_cols.head()

  Rank           Player  Age   Tm  First  Pts Won  Pts Max  Share
0    1  Dikembe Mutombo   34  TOT     48       48      123  0.390
1    2    Kevin Garnett   24  MIN     26       26      123  0.211
2    3       Tim Duncan   24  SAS     14       14      123  0.114
3    4    Doug Christie   30  SAC      9        9      123  0.073
4   5T   David Robinson   35  SAS      6        6      123  0.049

In [91]:
dpoy_final = dpoy_df_final_cols.rename(columns={
    "Rank": "voting_rank",
    "Player": "player_name",
    "Age": "age",
    "Tm": "team",
    "First": "first_place_votes",
    "Pts Won": "points_won",
    "Pts Max": "points_max",
    "Share": "vote_share"
}).copy()

dpoy_final["voting_rank"] = dpoy_final["voting_rank"].astype(str).str.replace("T","",regex=False).astype(int)

dpoy_final["season"] = "2000-2001"
dpoy_final["year"] = 2001

dpoy_final["award_winner"] = dpoy_final["voting_rank"] == 1

dpoy_final.head()

,voting_rank,player_name,age,team,first_place_votes,points_won,points_max,vote_share,season,year,award_winner
0,1,Dikembe Mutombo,34,TOT,48,48,123,0.390,2000-2001,2001,True
1,2,Kevin Garnett,24,MIN,26,26,123,0.211,2000-2001,2001,False
2,3,Tim Duncan,24,SAS,14,14,123,0.114,2000-2001,2001,False
3,4,Doug Christie,30,SAC,9,9,123,0.073,2000-2001,2001,False
4,5,David Robinson,35,SAS,6,6,123,0.049,2000-2001,2001,False

In [92]:
dpoy_final.isna().sum()

voting_rank          0
player_name          0
age                  0
team                 0
first_place_votes    0
points_won           0
points_max           0
vote_share           0
season               0
year                 0
award_winner         0
dtype: int64

In [97]:
rookie_df.head(12)

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 # Tm             Player                Age
0                 1st        Mike Miller               20.0
1                 1st      Kenyon Martin               23.0
2                 1st       Marc Jackson               26.0
3                 1st    Morris Peterson               23.0
4                 1st       Darius Miles               19.0
5                 NaN                NaN                NaN
6                 2nd      Hedo Türkoğlu               21.0
7                 2nd      Desmond Mason               23.0
8                 2nd       Marcus Fizer               22.0
9                 2nd         Chris Mihm               21.0
10                NaN                NaN                NaN
11                ORV    Jamaal Magloire               22.0

   Unnamed: 3_level_0  Voting                              Unnamed: 9_level_0  \
                   Tm Pts Won Pts Max  Share 1st Tm 2nd Tm                  G
0                 ORL    56.0    56.0  1.000   28.0    0.0               82.0
1                 NJN    54.0    56.0  0.964   27.0    0.0               68.0
2                 GSW    51.0    56.0  0.911   24.0    3.0               48.0
3                 TOR    50.0    56.0  0.893   22.0    6.0               80.0
4                 LAC    48.0    56.0  0.857   21.0    6.0               81.0
5                 NaN     NaN     NaN    NaN    NaN    NaN                NaN
6                 SAC    34.0    56.0  0.607    9.0   16.0               74.0
7                 SEA    28.0    56.0  0.500    5.0   18.0               78.0
8                 CHI    16.0    56.0  0.286    1.0   14.0               72.0
9                 CLE    13.0    56.0  0.232    1.0   11.0               59.0
10                NaN     NaN     NaN    NaN    NaN    NaN                NaN
11                CHH    12.0    56.0  0.214    0.0   12.0               74.0

    ... Per Game                     Shooting               Advanced
    ...      PTS  TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
0   ...     11.9  4.0  1.7  0.6  0.2    0.436  0.407  0.711      5.3  0.106
1   ...     12.0  7.4  1.9  1.1  1.7    0.445  0.091  0.630      2.1  0.044
2   ...     13.2  7.5  1.2  0.7  0.6    0.467  0.217  0.802      2.6  0.089
3   ...      9.3  3.2  1.3  0.8  0.3    0.431  0.382  0.717      3.6  0.096
4   ...      9.4  5.9  1.2  0.6  1.5    0.505  0.053  0.521      3.0  0.068
5   ...      NaN  NaN  NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
6   ...      5.3  2.8  0.9  0.7  0.3    0.412  0.326  0.777      2.8  0.106
7   ...      5.9  3.2  0.8  0.5  0.3    0.431  0.269  0.736      1.7  0.055
8   ...      9.5  4.3  1.1  0.4  0.3    0.430  0.256  0.727     -0.7 -0.022
9   ...      7.6  4.7  0.3  0.3  0.9    0.442  0.000  0.794      1.3  0.053
10  ...      NaN  NaN  NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
11  ...      4.6  4.0  0.4  0.2  1.1    0.450  0.000  0.655      2.6  0.114

[12 rows x 21 columns]

In [96]:
defense_df.head(12)

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 # Tm                Pos             Player
0                 1st                  C    Dikembe Mutombo
1                 1st                  F         Tim Duncan
2                 1st                  G         Jason Kidd
3                 1st                  G        Gary Payton
4                 1st                  F      Kevin Garnett
5                 NaN                NaN                NaN
6                 2nd                  G        Kobe Bryant
7                 2nd                  G      Doug Christie
8                 2nd                  F        Bruce Bowen
9                 2nd                  C   Shaquille O'Neal
10                2nd                  F         P.J. Brown
11                NaN                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0  Voting                 \
                  Age                 Tm Pts Won Pts Max  Share
0                34.0                TOT    43.0    58.0  0.741
1                24.0                SAS    40.0    58.0  0.690
2                27.0                PHO    39.0    58.0  0.672
3                32.0                SEA    38.0    58.0  0.655
4                24.0                MIN    24.0    58.0  0.414
5                 NaN                NaN     NaN     NaN    NaN
6                22.0                LAL    26.0    58.0  0.448
7                30.0                SAC    20.0    58.0  0.345
8                29.0                MIA    18.0    58.0  0.310
9                28.0                LAL    17.0    58.0  0.293
10               31.0                CHH    13.0    58.0  0.224
11                NaN                NaN     NaN     NaN    NaN

   Unnamed: 8_level_0 Per Game  ...           Shooting               Advanced  \
                    G       MP  ...  STL  BLK      FG%    3P%    FT%       WS
0                75.0     34.5  ...  0.4  2.7    0.484    NaN  0.725      8.1
1                82.0     38.7  ...  0.9  2.3    0.499  0.259  0.618     13.2
2                77.0     39.8  ...  2.2  0.3    0.411  0.297  0.814      9.6
3                79.0     41.1  ...  1.6  0.3    0.456  0.375  0.766     10.8
4                81.0     39.5  ...  1.4  1.8    0.477  0.288  0.764     11.8
5                 NaN      NaN  ...  NaN  NaN      NaN    NaN    NaN      NaN
6                68.0     40.9  ...  1.7  0.6    0.464  0.305  0.853     11.3
7                81.0     36.3  ...  2.3  0.6    0.395  0.376  0.897      8.7
8                82.0     32.7  ...  1.0  0.6    0.363  0.336  0.609      4.2
9                74.0     39.5  ...  0.6  2.8    0.572  0.000  0.513     14.9
10               80.0     35.1  ...  1.0  1.2    0.444  0.000  0.852      8.0
11                NaN      NaN  ...  NaN  NaN      NaN    NaN    NaN      NaN


    WS/48  DWS DBPM   DRtg
0   0.151  4.7  1.3   97.0
1   0.200  7.1  1.8   94.0
2   0.150  5.4  1.7   97.0
3   0.160  1.7 -0.7  107.0
4   0.176  4.8  1.4   99.0
5     NaN  NaN  NaN    NaN
6   0.196  2.2 -0.3  105.0
7   0.141  4.4  2.3   99.0
8   0.075  3.7  1.5  100.0
9   0.245  3.9  0.7  101.0
10  0.137  4.7  0.9   98.0
11    NaN  NaN  NaN    NaN

[12 rows x 23 columns]

In [101]:
rookie_df.columns = rookie_df.columns.get_level_values(-1)

defense_df.columns = defense_df.columns.get_level_values(-1)

rookie_df.head(15)

,# Tm,Player,Age,Tm,Pts Won,Pts Max,Share,1st Tm,2nd Tm,G,...,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1st,Mike Miller,20.0,ORL,56.0,56.0,1.000,28.0,0.0,82.0,...,11.9,4.0,1.7,0.6,0.2,0.436,0.407,0.711,5.3,0.106
1,1st,Kenyon Martin,23.0,NJN,54.0,56.0,0.964,27.0,0.0,68.0,...,12.0,7.4,1.9,1.1,1.7,0.445,0.091,0.630,2.1,0.044
2,1st,Marc Jackson,26.0,GSW,51.0,56.0,0.911,24.0,3.0,48.0,...,13.2,7.5,1.2,0.7,0.6,0.467,0.217,0.802,2.6,0.089
3,1st,Morris Peterson,23.0,TOR,50.0,56.0,0.893,22.0,6.0,80.0,...,9.3,3.2,1.3,0.8,0.3,0.431,0.382,0.717,3.6,0.096
4,1st,Darius Miles,19.0,LAC,48.0,56.0,0.857,21.0,6.0,81.0,...,9.4,5.9,1.2,0.6,1.5,0.505,0.053,0.521,3.0,0.068
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2nd,Hedo Türkoğlu,21.0,SAC,34.0,56.0,0.607,9.0,16.0,74.0,...,5.3,2.8,0.9,0.7,0.3,0.412,0.326,0.777,2.8,0.106
7,2nd,Desmond Mason,23.0,SEA,28.0,56.0,0.500,5.0,18.0,78.0,...,5.9,3.2,0.8,0.5,0.3,0.431,0.269,0.736,1.7,0.055
8,2nd,Marcus Fizer,22.0,CHI,16.0,56.0,0.286,1.0,14.0,72.0,...,9.5,4.3,1.1,0.4,0.3,0.430,0.256,0.727,-0.7,-0.022
9,2nd,Chris Mihm,21.0,CLE,13.0,56.0,0.232,1.0,11.0,59.0,...,7.6,4.7,0.3,0.3,0.9,0.442,0.000,0.794,1.3,0.053
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ORV,Jamaal Magloire,22.0,CHH,12.0,56.0,0.214,0.0,12.0,74.0,...,4.6,4.0,0.4,0.2,1.1,0.450,0.000,0.655,2.6,0.114
12,ORV,Quentin Richardson,20.0,LAC,11.0,56.0,0.196,3.0,5.0,76.0,...,8.1,3.4,0.8,0.6,0.1,0.442,0.331,0.627,3.0,0.106
13,ORV,Mateen Cleaves,23.0,DET,11.0,56.0,0.196,1.0,9.0,78.0,...,5.4,1.7,2.7,0.6,0.0,0.400,0.294,0.708,-0.1,-0.006
14,ORV,Keyon Dooling,20.0,LAC,9.0,56.0,0.161,0.0,9.0,76.0,...,5.9,1.2,2.3,0.5,0.1,0.409,0.350,0.698,1.4,0.056

In [104]:
rookie_df_cleaned = rookie_df[["# Tm", "Player", "Age", "Tm", "Pts Won", "Pts Max", "Share", "1st Tm", "2nd Tm"]].copy()

defense_df_cleaned =defense_df[["# Tm", "Player", "Age", "Tm", "Pts Won", "Pts Max", "Share"]].copy()

defense_df_cleaned.head()

  # Tm           Player   Age   Tm  Pts Won  Pts Max  Share
0  1st  Dikembe Mutombo  34.0  TOT     43.0     58.0  0.741
1  1st       Tim Duncan  24.0  SAS     40.0     58.0  0.690
2  1st       Jason Kidd  27.0  PHO     39.0     58.0  0.672
3  1st      Gary Payton  32.0  SEA     38.0     58.0  0.655
4  1st    Kevin Garnett  24.0  MIN     24.0     58.0  0.414

In [110]:
rookie_df_cleaner = rookie_df_cleaned[rookie_df_cleaned["# Tm"].notna()].copy()
defense_df_cleaner = defense_df_cleaned[defense_df_cleaned["# Tm"].notna()].copy()

defense_df_cleaner.head(15)

   # Tm            Player   Age   Tm  Pts Won  Pts Max  Share
0   1st   Dikembe Mutombo  34.0  TOT     43.0     58.0  0.741
1   1st        Tim Duncan  24.0  SAS     40.0     58.0  0.690
2   1st        Jason Kidd  27.0  PHO     39.0     58.0  0.672
3   1st       Gary Payton  32.0  SEA     38.0     58.0  0.655
4   1st     Kevin Garnett  24.0  MIN     24.0     58.0  0.414
6   2nd       Kobe Bryant  22.0  LAL     26.0     58.0  0.448
7   2nd     Doug Christie  30.0  SAC     20.0     58.0  0.345
8   2nd       Bruce Bowen  29.0  MIA     18.0     58.0  0.310
9   2nd  Shaquille O'Neal  28.0  LAL     17.0     58.0  0.293
10  2nd        P.J. Brown  31.0  CHH     13.0     58.0  0.224
12  ORV    David Robinson  35.0  SAS     13.0     58.0  0.224
13  ORV     Allen Iverson  25.0  PHI     12.0     58.0  0.207
14  ORV      Shawn Marion  22.0  PHO     12.0     58.0  0.207
15  ORV         Eric Snow  27.0  PHI     12.0     58.0  0.207
16  ORV       Karl Malone  37.0  UTA      9.0     58.0  0.155

In [114]:
rookie_df_cleaner.info()

<class 'pandas.DataFrame'>
Index: 21 entries, 0 to 22
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   # Tm     21 non-null     str
 1   Player   21 non-null     str
 2   Age      21 non-null     float64
 3   Tm       21 non-null     str
 4   Pts Won  21 non-null     float64
 5   Pts Max  21 non-null     float64
 6   Share    21 non-null     float64
 7   1st Tm   21 non-null     float64
 8   2nd Tm   21 non-null     float64
dtypes: float64(6), str(3)
memory usage: 1.6 KB

In [116]:
rookie_final = rookie_df_cleaner.rename(columns={
    "# Tm": "team_selection",
    "Player": "player_name",
    "Age": "age",
    "Tm": "team",
    "Pts Won": "points_won",
    "Pts Max": "points_max",
    "Share": "vote_share",
    "1st Tm": "first_team_votes",
    "2nd Tm": "second_team_votes"
}).copy()

defense_final = defense_df_cleaner.rename(columns={
    "# Tm": "team_selection",
    "Pos": "position",
    "Player": "player_name",
    "Age": "age",
    "Tm": "team",
    "Pts Won": "points_won",
    "Pts Max": "points_max",
    "Share": "vote_share"
}).copy()

rookie_final["season"] = "2000-2001"
rookie_final["year"] = 2001

defense_final["season"] = "2000-2001"
defense_final["year"] = 2001

rookie_final[[
    "age",
    "points_won",
    "points_max",
    "first_team_votes",
    "second_team_votes"
]] = rookie_final[[
    "age",
    "points_won",
    "points_max",
    "first_team_votes",
    "second_team_votes"
]].astype(int)

defense_final[[
    "age",
    "points_won",
    "points_max"
]] = defense_final[[
    "age",
    "points_won",
    "points_max"
]].astype(int)

In [120]:
rookie_final.info()

<class 'pandas.DataFrame'>
Index: 21 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   team_selection     21 non-null     str
 1   player_name        21 non-null     str
 2   age                21 non-null     int64
 3   team               21 non-null     str
 4   points_won         21 non-null     int64
 5   points_max         21 non-null     int64
 6   vote_share         21 non-null     float64
 7   first_team_votes   21 non-null     int64
 8   second_team_votes  21 non-null     int64
 9   season             21 non-null     str
 10  year               21 non-null     int64
dtypes: float64(1), int64(6), str(4)
memory usage: 2.0 KB

In [121]:

import pandas as pd
import requests
import certifi
from bs4 import BeautifulSoup, Comment
from io import StringIO

def extract_awards(year):

    # STAGE 1: Construct the URL
    url = f"https://www.basketball-reference.com/awards/awards_{year}.html"

    # STAGE 2: Download and parse the webpage
    response = requests.get(url, verify=certifi.where(), timeout=20)
    response.raise_for_status()

    html = response.content.decode("utf-8")
    soup = BeautifulSoup(html, "html.parser")

    # STAGE 3: Collect regular and commented-out HTML tables
    all_tables = soup.find_all("table")

    comments = soup.find_all(
        string=lambda text: isinstance(text, Comment)
    )

    for comment in comments:
        comment_soup = BeautifulSoup(comment, "html.parser")
        all_tables.extend(comment_soup.find_all("table"))

    # STAGE 4: Identify the five award tables
    table_ids = {
        "mvp": "mvp",
        "roy": "roy",
        "dpoy": "dpoy",
        "rookie": "leading_all_rookie",
        "defense": "leading_all_defense"
    }

    # STAGE 5: Convert each HTML table into a DataFrame
    extracted = {}

    for name, table_id in table_ids.items():

        table = next(
            table for table in all_tables
            if table.get("id") == table_id
        )

        extracted[name] = pd.read_html(StringIO(str(table)))[0]

    # STAGE 6: Return the five DataFrames
    return extracted

awards_2013 = extract_awards(2013)

In [122]:
awards_2013

{'mvp':    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rank             Player                Age
 0                   1       LeBron James                 28
 1                   2       Kevin Durant                 24
 2                   3    Carmelo Anthony                 28
 3                   4         Chris Paul                 27
 4                   5        Kobe Bryant                 34
 5                   6        Tony Parker                 30
 6                   7         Tim Duncan                 36
 7                   8       James Harden                 23
 8                   9  Russell Westbrook                 24
 9                  10        Dwyane Wade                 31
 10                 11      Stephen Curry                 24
 11                12T      Kevin Garnett                 36
 12                12T         Marc Gasol                 28
 13                12T          Ty Lawson                 25
 14                12T          David Lee                 29
 15                12T        Joakim Noah                 27

    Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                    Tm  First Pts Won Pts Max  Share                  G
 0                 MIA    120    1207    1210  0.998                 76
 1                 OKC      0     765    1210  0.632                 81
 2                 NYK      1     475    1210  0.393                 67
 3                 LAC      0     289    1210  0.239                 70
 4                 LAL      0     184    1210  0.152                 78
 5                 SAS      0      86    1210  0.071                 66
 6                 SAS      0      65    1210  0.054                 69
 7                 HOU      0      33    1210  0.027                 78
 8                 OKC      0       9    1210  0.007                 82
 9                 MIA      0       5    1210  0.004                 69
 10                GSW      0       3    1210  0.002                 78
 11                BOS      0       1    1210  0.001                 68
 12                MEM      0       1    1210  0.001                 80
 13                DEN      0       1    1210  0.001                 73
 14                GSW      0       1    1210  0.001                 79
 15                CHI      0       1    1210  0.001                 66

    Per Game                            Shooting               Advanced
          MP   PTS   TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
 0      37.9  26.8   8.0  7.3  1.7  0.9    0.565  0.406  0.753     19.3  0.322
 1      38.5  28.1   7.9  4.6  1.4  1.3    0.510  0.416  0.905     18.9  0.291
 2      37.0  28.7   6.9  2.6  0.8  0.5    0.449  0.379  0.830      9.5  0.184
 3      33.4  16.9   3.7  9.7  2.4  0.1    0.481  0.328  0.885     13.9  0.287
 4      38.6  27.3   5.6  6.0  1.4  0.3    0.463  0.324  0.839     10.9  0.174
 5      32.9  20.3   3.0  7.6  0.8  0.1    0.522  0.353  0.845      9.3  0.206
 6      30.1  17.8   9.9  2.7  0.7  2.7    0.502  0.286  0.817      8.3  0.191
 7      38.3  25.9   4.9  5.8  1.8  0.5    0.438  0.368  0.851     12.8  0.206
 8      34.9  23.2   5.2  7.4  1.8  0.3    0.438  0.323  0.800     11.6  0.195
 9      34.7  21.2   5.0  5.1  1.9  0.8    0.521  0.258  0.725      9.6  0.192
 10     38.2  22.9   4.0  6.9  1.6  0.2    0.451  0.453  0.900     11.2  0.180
 11     29.7  14.8   7.8  2.3  1.1  0.9    0.496  0.125  0.786      5.6  0.133
 12     35.0  14.1   7.8  4.0  1.0  1.7    0.494  0.071  0.848     11.5  0.197
 13     34.4  16.7   2.7  6.9  1.5  0.1    0.461  0.366  0.756      7.4  0.141
 14     36.8  18.5  11.2  3.5  0.8  0.3    0.519  0.000  0.797      9.1  0.150
 15     36.8  11.9  11.1  4.0  1.2  2.1    0.481  0.000  0.751      7.3  0.145  ,
 'roy':   Unnamed: 0_level_0      Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Rank                  Player                Age
 0                  1          Damian Lillard                 22
 1                  2           Anthony Davis                 19
 2                  3            Bradley Beal                 19
 3                  4          Andre Drummond                 19
 4                  5            Dion Waiters                 21
 5                 6T         Harrison Barnes                 20
 6                 6T          Chris Copeland                 28
 7                  8  Michael Kidd-Gilchrist                 19
 8                  9       Jonas Valančiūnas                 20
 9                 10            John Jenkins                 21

   Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                   Tm  First Pts Won Pts Max  Share                  G
 0                POR    121     605     605  1.000                 82
 1                NOH      0     306     605  0.506                 64
 2                WAS      0      94     605  0.155                 56
 3                DET      0      36     605  0.060                 60
 4                CLE      0      21     605  0.035                 61
 5                GSW      0       8     605  0.013                 81
 6                NYK      0       8     605  0.013                 56
 7                CHA      0       3     605  0.005                 78
 8                TOR      0       2     605  0.003                 62
 9                ATL      0       1     605  0.002                 61

   Per Game                           Shooting               Advanced
         MP   PTS  TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
 0     38.6  19.0  3.1  6.5  0.9  0.2    0.429  0.368  0.844      5.8  0.088
 1     28.8  13.5  8.2  1.0  1.2  1.8    0.516  0.000  0.751      6.1  0.159
 2     31.2  13.9  3.8  2.4  0.9  0.5    0.410  0.386  0.786      3.0  0.082
 3     20.7   7.9  7.6  0.5  1.0  1.6    0.608  0.500  0.371      4.5  0.172
 4     28.8  14.7  2.4  3.0  1.0  0.3    0.412  0.310  0.746      0.9  0.026
 5     25.4   9.2  4.1  1.2  0.6  0.2    0.439  0.359  0.758      2.8  0.065
 6     15.4   8.7  2.1  0.5  0.3  0.2    0.479  0.421  0.759      2.1  0.117
 7     26.0   9.0  5.8  1.5  0.7  0.9    0.458  0.222  0.749      2.1  0.051
 8     23.9   8.9  6.0  0.7  0.3  1.3    0.557    NaN  0.789      3.9  0.127
 9     14.8   6.1  1.5  0.9  0.2  0.2    0.446  0.384  0.843      1.7  0.091  ,
 'dpoy':    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rank             Player                Age
 0                   1         Marc Gasol                 28
 1                   2       LeBron James                 28
 2                   3        Serge Ibaka                 23
 3                   4        Joakim Noah                 27
 4                   5         Tony Allen                 31
 5                   6         Tim Duncan                 36
 6                   7      Larry Sanders                 24
 7                   8        Paul George                 22
 8                   9     Andre Iguodala                 29
 9                  10        Roy Hibbert                 26
 10                 11         Chris Paul                 27
 11                 12      Avery Bradley                 22
 12                 13     Tyson Chandler                 30
 13                 14      Dwight Howard                 27
 14                 15          Luol Deng                 27
 15                 16        Dwyane Wade                 31
 16                17T       Trevor Ariza                 27
 17                17T       Jimmy Butler                 23
 18                17T     Kenneth Faried                 23
 19                17T  Russell Westbrook                 24
 20                 21        Mike Conley                 25

    Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                    Tm  First Pts Won Pts Max  Share                  G
 0                 MEM     30     212     605  0.350                 80
 1                 MIA     18     149     605  0.246                 76
 2                 OKC     14     122     605  0.202                 80
 3                 CHI     13     107     605  0.177                 66
 4                 MEM      9     102     605  0.169                 79
 5                 SAS     11      94     605  0.155                 69
 6                 MIL      4      90     605  0.149                 71
 7                 IND      8      57     605  0.094                 79
 8                 DEN      5      43     605  0.071                 80
 9                 IND      3      36     605  0.060                 79
 10                LAC      2      19     605  0.031                 70
 11                BOS      2      15     605  0.025                 50
 12                NYK      0      11     605  0.018                 66
 13                LAL      1       9     605  0.015                 76
 14                CHI      1       6     605  0.010                 75
 15                MIA      0       4     605  0.007                 69
 16                WAS      0       3     605  0.005                 56
 17                CHI      0       3     605  0.005                 82
 18                DEN      0       3     605  0.005                 80
 19                OKC      0       3     605  0.005                 82
 20                MEM      0       1     605  0.002                 80

    Per Game  ...           Shooting               Advanced                   \
          MP  ...  STL  BLK      FG%    3P%    FT%       WS  WS/48  DWS DBPM
 0      35.0  ...  1.0  1.7    0.494  0.071  0.848     11.5  0.197  5.4  3.1
 1      37.9  ...  1.7  0.9    0.565  0.406  0.753     19.3  0.322  4.7  2.4
 2      31.1  ...  0.4  3.0    0.573  0.351  0.749      9.4  0.181  4.1  0.7
 3      36.8  ...  1.2  2.1    0.481  0.000  0.751      7.3  0.145  4.7  2.7
 4      26.7  ...  1.5  0.6    0.445  0.125  0.717      5.1  0.115  4.1  2.4
 5      30.1  ...  0.7  2.7    0.502  0.286  0.817      8.3  0.191  4.9  2.9
 6      27.3  ...  0.7  2.8    0.506  0.000  0.618      6.0  0.149  3.7  2.0
 7      37.6  ...  1.8  0.6    0.419  0.362  0.807      9.0  0.145  6.3  2.3
 8      34.7  ...  1.7  0.7    0.451  0.317  0.574      5.6  0.097  3.2  1.4
 9      28.7  ...  0.5  2.6    0.448  0.250  0.741      6.1  0.129  4.9  1.4
 10     33.4  ...  2.4  0.1    0.481  0.328  0.885     13.9  0.287  3.4  2.4
 11     28.7  ...  1.3  0.4    0.402  0.317  0.755      0.4  0.012  1.6  0.3
 12     32.8  ...  0.6  1.1    0.638    NaN  0.694      9.3  0.207  2.6 -0.3
 13     35.8  ...  1.1  2.4    0.578  0.167  0.492      7.6  0.134  4.8  1.1
 14     38.7  ...  1.1  0.4    0.426  0.322  0.816      6.3  0.105  3.3 -0.3
 15     34.7  ...  1.9  0.8    0.521  0.258  0.725      9.6  0.192  3.5  0.7
 16     26.3  ...  1.3  0.4    0.417  0.364  0.821      3.1  0.102  2.4  2.0
 17     26.0  ...  1.0  0.4    0.467  0.381  0.803      7.0  0.158  2.6  1.0
 18     28.1  ...  1.0  1.0    0.552    NaN  0.613      7.8  0.167  3.4  0.2
 19     34.9  ...  1.8  0.3    0.438  0.323  0.800     11.6  0.195  3.9 -0.2
 20     34.5  ...  2.2  0.3    0.440  0.362  0.830      9.9  0.172  4.7  2.3


    DRtg
 0    98
 1   101
 2   101
 3    99
 4    98
 5    95
 6    99
 7    97
 8   105
 9    97
 10  102
 11  105
 12  104
 13  100
 14  105
 15  103
 16  101
 17  104
 18  102
 19  103
 20  100

 [21 rows x 23 columns],
 'rookie':    Unnamed: 0_level_0      Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  # Tm                  Player                Age
 0                 1st          Damian Lillard               22.0
 1                 1st            Bradley Beal               19.0
 2                 1st           Anthony Davis               19.0
 3                 1st            Dion Waiters               21.0
 4                 1st         Harrison Barnes               20.0
 5                 NaN                     NaN                NaN
 6                 2nd          Andre Drummond               19.0
 7                 2nd       Jonas Valančiūnas               20.0
 8                 2nd  Michael Kidd-Gilchrist               19.0
 9                 2nd            Kyle Singler               24.0
 10                2nd            Tyler Zeller               23.0
 11                NaN                     NaN                NaN
 12                ORV        Maurice Harkless               19.0
 13                ORV            Alexey Shved               24.0
 14                ORV          Chris Copeland               28.0
 15                ORV           Brian Roberts               27.0
 16                ORV        Andrew Nicholson               23.0
 17                ORV             Jae Crowder               22.0
 18                ORV            Festus Ezeli               23.0
 19                ORV          Draymond Green               22.0
 20                ORV            John Jenkins               21.0
 21                ORV          Terrence Jones               21.0
 22                ORV          Pablo Prigioni               35.0
 23                ORV           Terrence Ross               21.0
 24                ORV             Jeff Taylor               23.0

    Unnamed: 3_level_0  Voting                              Unnamed: 9_level_0  \
                    Tm Pts Won Pts Max  Share 1st Tm 2nd Tm                  G
 0                 POR    58.0    58.0  1.000   29.0    0.0               82.0
 1                 WAS    57.0    58.0  0.983   28.0    1.0               56.0
 2                 NOH    57.0    58.0  0.983   28.0    1.0               64.0
 3                 CLE    50.0    58.0  0.862   21.0    8.0               61.0
 4                 GSW    47.0    58.0  0.810   18.0   11.0               81.0
 5                 NaN     NaN     NaN    NaN    NaN    NaN                NaN
 6                 DET    35.0    58.0  0.603   10.0   15.0               60.0
 7                 TOR    31.0    58.0  0.534    6.0   19.0               62.0
 8                 CHA    29.0    58.0  0.500    3.0   23.0               78.0
 9                 DET    17.0    58.0  0.293    1.0   15.0               82.0
 10                CLE    15.0    58.0  0.259    3.0    9.0               77.0
 11                NaN     NaN     NaN    NaN    NaN    NaN                NaN
 12                ORL    14.0    58.0  0.241    1.0   12.0               76.0
 13                MIN    14.0    58.0  0.241    1.0   12.0               77.0
 14                NYK     9.0    58.0  0.155    1.0    7.0               56.0
 15                NOH     5.0    58.0  0.086    0.0    5.0               78.0
 16                ORL     4.0    58.0  0.069    0.0    4.0               75.0
 17                DAL     1.0    58.0  0.017    0.0    1.0               78.0
 18                GSW     1.0    58.0  0.017    0.0    1.0               78.0
 19                GSW     1.0    58.0  0.017    0.0    1.0               79.0
 20                ATL     1.0    58.0  0.017    0.0    1.0               61.0
 21                HOU     1.0    58.0  0.017    0.0    1.0               19.0
 22                NYK     1.0    58.0  0.017    0.0    1.0               78.0
 23                TOR     1.0    58.0  0.017    0.0    1.0               73.0
 24                CHA     1.0    58.0  0.017    0.0    1.0               77.0

     ... Per Game                     Shooting               Advanced
     ...      PTS  TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
 0   ...     19.0  3.1  6.5  0.9  0.2    0.429  0.368  0.844      5.8  0.088
 1   ...     13.9  3.8  2.4  0.9  0.5    0.410  0.386  0.786      3.0  0.082
 2   ...     13.5  8.2  1.0  1.2  1.8    0.516  0.000  0.751      6.1  0.159
 3   ...     14.7  2.4  3.0  1.0  0.3    0.412  0.310  0.746      0.9  0.026
 4   ...      9.2  4.1  1.2  0.6  0.2    0.439  0.359  0.758      2.8  0.065
 5   ...      NaN  NaN  NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
 6   ...      7.9  7.6  0.5  1.0  1.6    0.608  0.500  0.371      4.5  0.172
 7   ...      8.9  6.0  0.7  0.3  1.3    0.557    NaN  0.789      3.9  0.127
 8   ...      9.0  5.8  1.5  0.7  0.9    0.458  0.222  0.749      2.1  0.051
 9   ...      8.8  4.0  0.9  0.7  0.5    0.428  0.350  0.806      2.3  0.048
 10  ...      7.9  5.7  1.2  0.5  0.9    0.438  0.000  0.764      2.0  0.048
 11  ...      NaN  NaN  NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
 12  ...      8.2  4.4  0.7  1.2  0.8    0.461  0.274  0.570      2.4  0.059
 13  ...      8.6  2.3  3.7  0.7  0.4    0.372  0.295  0.720      0.8  0.020
 14  ...      8.7  2.1  0.5  0.3  0.2    0.479  0.421  0.759      2.1  0.117
 15  ...      7.1  1.2  2.8  0.5  0.0    0.417  0.386  0.909      2.2  0.078
 16  ...      7.8  3.4  0.6  0.3  0.4    0.527    NaN  0.798      1.7  0.065
 17  ...      5.0  2.4  1.2  0.8  0.2    0.384  0.328  0.644      1.5  0.055
 18  ...      2.4  4.0  0.3  0.3  0.9    0.438    NaN  0.531      1.5  0.066
 19  ...      2.9  3.3  0.7  0.5  0.3    0.327  0.209  0.818      0.6  0.028
 20  ...      6.1  1.5  0.9  0.2  0.2    0.446  0.384  0.843      1.7  0.091
 21  ...      5.5  3.4  0.8  0.6  1.0    0.457  0.263  0.765      0.7  0.128
 22  ...      3.5  1.8  3.0  0.9  0.0    0.455  0.396  0.880      3.2  0.123
 23  ...      6.4  2.0  0.7  0.6  0.2    0.407  0.332  0.714      0.9  0.034
 24  ...      6.1  1.9  0.8  0.6  0.2    0.431  0.344  0.728      1.2  0.039

 [25 rows x 21 columns],
 'defense':    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  # Tm                Pos             Player
 0                 1st                  G         Tony Allen
 1                 1st                  F       LeBron James
 2                 1st                  F        Serge Ibaka
 3                 1st                  G         Chris Paul
 4                 1st                  C     Tyson Chandler
 5                 1st                  C        Joakim Noah
 6                 NaN                NaN                NaN
 7                 2nd                  F        Paul George
 8                 2nd                  G      Avery Bradley
 9                 2nd                  F         Tim Duncan
 10                2nd                  G        Mike Conley
 11                2nd                  C         Marc Gasol
 12                NaN                NaN                NaN
 13                ORV                  F     Andre Iguodala
 14                ORV                  F      Larry Sanders
 15                ORV                  G    Thabo Sefolosha
 16                ORV                  F          Luol Deng
 17                ORV                  C      Dwight Howard
 18                ORV                  G        Kobe Bryant
 19                ORV                  C        Roy Hibbert
 20                ORV                  F     Kenneth Faried
 21                ORV                  G  Russell Westbrook
 22                ORV                  F      Shane Battier
 23                ORV                  F      Nicolas Batum
 24                ORV                  F       Corey Brewer
 25                ORV                  G        George Hill
 26                ORV                  G         Mike James
 27                ORV                  F      Kawhi Leonard
 28                ORV                  G        Tony Parker
 29                ORV                  G        Dwyane Wade
 30                ORV                  F  Metta World Peace
 31                ORV                  G       Eric Bledsoe
 32                ORV                  F       Kevin Durant
 33                ORV                  G       Jrue Holiday
 34                ORV                  F   Andrei Kirilenko
 35                ORV                  G      Iman Shumpert
 36                ORV                  F         David West

    Unnamed: 3_level_0 Unnamed: 4_level_0  Voting                 \

In [124]:
awards_2026 = extract_awards(2026)

awards_2026

{'mvp':   Unnamed: 0_level_0       Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Rank                   Player                Age
 0                  1  Shai Gilgeous-Alexander                 27
 1                  2             Nikola Jokić                 30
 2                  3        Victor Wembanyama                 22
 3                  4              Luka Dončić                 26
 4                  5          Cade Cunningham                 24
 5                  6             Jaylen Brown                 29
 6                 7T            Kawhi Leonard                 34
 7                 7T         Donovan Mitchell                 29

   Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                   Tm  First Pts Won Pts Max  Share                  G
 0                OKC     83     939    1000  0.939                 68
 1                DEN     10     634    1000  0.634                 65
 2                SAS      5     569    1000  0.569                 64
 3                LAL      0     250    1000  0.250                 64
 4                DET      2     117    1000  0.117                 64
 5                BOS      0      89    1000  0.089                 71
 6                LAC      0       1    1000  0.001                 65
 7                CLE      0       1    1000  0.001                 70

   Per Game                             Shooting               Advanced
         MP   PTS   TRB   AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
 0     33.2  31.1   4.3   6.6  1.4  0.8    0.553  0.386  0.879     15.2  0.323
 1     34.8  27.7  12.9  10.7  1.4  0.8    0.569  0.380  0.831     14.9  0.316
 2     29.2  25.0  11.5   3.1  1.0  3.1    0.512  0.349  0.827     10.0  0.257
 3     35.8  33.5   7.7   8.3  1.6  0.5    0.476  0.366  0.780      9.5  0.199
 4     33.9  23.9   5.5   9.9  1.4  0.8    0.461  0.342  0.812      7.9  0.174
 5     34.4  28.7   6.9   5.1  1.0  0.4    0.477  0.347  0.795      6.9  0.135
 6     32.1  27.9   6.4   3.6  1.9  0.4    0.505  0.387  0.892      9.2  0.212
 7     33.5  27.9   4.5   5.7  1.5  0.3    0.483  0.364  0.865      8.2  0.169  ,
 'roy':   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                 Rank             Player                Age                 Tm
 0                  1       Cooper Flagg                 19                DAL
 1                  2       Kon Knueppel                 20                CHO
 2                  3       VJ Edgecombe                 20                PHI
 3                  4       Dylan Harper                 19                SAS
 4                  5      Cedric Coward                 22                MEM

   Voting                        Unnamed: 8_level_0 Per Game                  \
    First Pts Won Pts Max  Share                  G       MP   PTS  TRB  AST
 0     56     412     500  0.824                 70     33.5  21.0  6.7  4.5
 1     44     386     500  0.772                 81     31.5  18.5  5.3  3.4
 2      0      96     500  0.192                 75     35.0  16.0  5.6  4.2
 3      0       5     500  0.010                 69     22.6  11.8  3.4  3.9
 4      0       1     500  0.002                 62     25.8  13.6  5.9  2.8

             Shooting               Advanced
    STL  BLK      FG%    3P%    FT%       WS  WS/48
 0  1.2  0.9    0.468  0.295  0.827      3.8  0.078
 1  0.7  0.2    0.475  0.425  0.863      8.0  0.151
 2  1.4  0.5    0.438  0.354  0.818      4.4  0.081
 3  0.8  0.3    0.505  0.343  0.756      4.2  0.130
 4  0.6  0.4    0.471  0.338  0.843      2.5  0.076  ,
 'dpoy':    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rank             Player                Age
 0                   1  Victor Wembanyama                 22
 1                   2      Chet Holmgren                 23
 2                   3     Ausar Thompson                 23
 3                   4        Rudy Gobert                 33
 4                   5     Scottie Barnes                 24
 5                   6      Derrick White                 31
 6                   7      Cason Wallace                 22
 7                   8      Amen Thompson                 23
 8                   9      Dyson Daniels                 22
 9                  10         OG Anunoby                 28
 10                11T        Bam Adebayo                 28
 11                11T        Jalen Duren                 22
 12                11T     Draymond Green                 35

    Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                    Tm  First Pts Won Pts Max  Share                  G
 0                 SAS    100     500     500  1.000                 64
 1                 OKC      0     239     500  0.478                 69
 2                 DET      0      60     500  0.120                 73
 3                 MIN      0      41     500  0.082                 76
 4                 TOR      0      21     500  0.042                 80
 5                 BOS      0      13     500  0.026                 77
 6                 OKC      0       8     500  0.016                 77
 7                 HOU      0       6     500  0.012                 79
 8                 ATL      0       5     500  0.010                 76
 9                 NYK      0       4     500  0.008                 67
 10                MIA      0       1     500  0.002                 73
 11                DET      0       1     500  0.002                 70
 12                GSW      0       1     500  0.002                 68

    Per Game  ...           Shooting               Advanced                   \
          MP  ...  STL  BLK      FG%    3P%    FT%       WS  WS/48  DWS DBPM
 0      29.2  ...  1.0  3.1    0.512  0.349  0.827     10.0  0.257  5.0  4.2
 1      28.9  ...  0.6  1.9    0.557  0.362  0.792      9.1  0.219  4.7  1.9
 2      26.0  ...  2.0  0.9    0.525  0.250  0.571      5.7  0.144  4.1  3.6
 3      31.3  ...  0.8  1.6    0.682  0.000  0.526      8.7  0.176  4.0  0.9
 4      33.5  ...  1.4  1.5    0.507  0.304  0.815      7.8  0.140  4.5  2.3
 5      34.1  ...  1.1  1.3    0.394  0.327  0.902      7.0  0.129  3.5  1.0
 6      26.6  ...  1.9  0.4    0.432  0.351  0.809      5.2  0.122  4.2  3.3
 7      37.4  ...  1.5  0.6    0.534  0.216  0.779     10.3  0.167  3.8  1.0
 8      33.2  ...  2.0  0.4    0.517  0.188  0.615      6.6  0.126  3.6  1.8
 9      33.2  ...  1.6  0.7    0.484  0.386  0.828      6.3  0.135  3.2  1.1
 10     32.4  ...  1.2  0.7    0.442  0.318  0.778      6.4  0.129  3.6  0.4
 11     28.2  ...  0.8  0.8    0.650    NaN  0.747     11.0  0.266  3.8  0.5
 12     27.5  ...  0.9  0.6    0.418  0.326  0.702      1.7  0.044  2.1  1.0


    DRtg
 0   101
 1   104
 2   105
 3   110
 4   110
 5   113
 6   107
 7   114
 8   112
 9   112
 10  111
 11  108
 12  115

 [13 rows x 23 columns],
 'rookie':    Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  # Tm                Player                Age
 0                 1st          VJ Edgecombe               20.0
 1                 1st          Cooper Flagg               19.0
 2                 1st          Kon Knueppel               20.0
 3                 1st          Dylan Harper               19.0
 4                 1st         Cedric Coward               22.0
 5                 NaN                   NaN                NaN
 6                 2nd        Maxime Raynaud               22.0
 7                 2nd           Derik Queen               21.0
 8                 2nd        Jeremiah Fears               19.0
 9                 2nd            Ace Bailey               19.0
 10                2nd  Collin Murray-Boyles               20.0
 11                NaN                   NaN                NaN
 12                ORV      Ryan Kalkbrenner               24.0
 13                ORV           Tre Johnson               19.0
 14                ORV         Hugo González               19.0
 15                ORV            Will Riley               19.0
 16                ORV         Carter Bryant               20.0
 17                ORV            Egor Dëmin               19.0
 18                ORV            Sion James               23.0
 19                ORV   Kasparas Jakučionis               19.0
 20                ORV         Ryan Nembhard               22.0

    Unnamed: 3_level_0  Voting                              Unnamed: 9_level_0  \
                    Tm Pts Won Pts Max  Share 1st Tm 2nd Tm                  G
 0                 PHI   200.0   200.0  1.000  100.0    0.0               75.0
 1                 DAL   200.0   200.0  1.000  100.0    0.0               70.0
 2                 CHO   200.0   200.0  1.000  100.0    0.0               81.0
 3                 SAS   193.0   200.0  0.965   93.0    7.0               69.0
 4                 MEM   125.0   200.0  0.625   29.0   67.0               62.0
 5                 NaN     NaN     NaN    NaN    NaN    NaN                NaN
 6                 SAC   110.0   200.0  0.550   26.0   58.0               74.0
 7                 NOP   110.0   200.0  0.550   16.0   78.0               81.0
 8                 NOP   109.0   200.0  0.545   17.0   75.0               82.0
 9                 UTA   107.0   200.0  0.535   11.0   85.0               72.0
 10                TOR    66.0   200.0  0.330    8.0   50.0               57.0
 11                NaN     NaN     NaN    NaN    NaN    NaN                NaN
 12                CHO    43.0   200.0  0.215    0.0   43.0               69.0
 13                WAS    19.0   200.0  0.095    0.0   19.0               60.0
 14                BOS     5.0   200.0  0.025    0.0    5.0               74.0
 15                WAS     4.0   200.0  0.020    0.0    4.0               74.0
 16                SAS     3.0   200.0  0.015    0.0    3.0               71.0
 17                BRK     2.0   200.0  0.010    0.0    2.0               52.0
 18                CHO     2.0   200.0  0.010    0.0    2.0               82.0
 19                MIA     1.0   200.0  0.005    0.0    1.0               53.0
 20                DAL     1.0   200.0  0.005    0.0    1.0               60.0

     ... Per Game                     Shooting               Advanced
     ...      PTS  TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
 0   ...     16.0  5.6  4.2  1.4  0.5    0.438  0.354  0.818      4.4  0.081
 1   ...     21.0  6.7  4.5  1.2  0.9    0.468  0.295  0.827      3.8  0.078
 2   ...     18.5  5.3  3.4  0.7  0.2    0.475  0.425  0.863      8.0  0.151
 3   ...     11.8  3.4  3.9  0.8  0.3    0.505  0.343  0.756      4.2  0.130
 4   ...     13.6  5.9  2.8  0.6  0.4    0.471  0.338  0.843      2.5  0.076
 5   ...      NaN  NaN  NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
 6   ...     12.5  7.5  1.4  0.5  0.5    0.571  0.324  0.786      3.6  0.088
 7   ...     11.7  7.1  3.7  1.0  0.9    0.473  0.261  0.795      2.7  0.063
 8   ...     14.3  3.7  3.4  1.2  0.4    0.434  0.330  0.789      0.6  0.015
 9   ...     13.8  4.2  1.8  0.8  0.7    0.443  0.344  0.750     -0.1 -0.001
 10  ...      8.5  5.0  1.9  0.9  0.9    0.579  0.340  0.657      4.0  0.154
 11  ...      NaN  NaN  NaN  NaN  NaN      NaN    NaN    NaN      NaN    NaN
 12  ...      7.6  5.5  0.8  0.5  1.5    0.753  0.000  0.716      5.7  0.185
 13  ...     12.2  2.8  2.0  0.6  0.3    0.419  0.358  0.874     -0.7 -0.024
 14  ...      3.9  3.3  0.5  0.6  0.3    0.476  0.362  0.500      2.2  0.099
 15  ...     10.3  2.9  2.0  0.7  0.1    0.439  0.316  0.800      0.4  0.012
 16  ...      4.2  2.5  0.7  0.2  0.3    0.408  0.335  0.714      1.3  0.076
 17  ...     10.3  3.2  3.3  0.8  0.3    0.399  0.385  0.831      0.9  0.032
 18  ...      5.4  3.5  2.0  0.6  0.2    0.371  0.352  0.837      3.1  0.080
 19  ...      6.2  2.6  2.6  0.6  0.1    0.429  0.423  0.879      2.3  0.114
 20  ...      6.6  2.2  5.3  0.4  0.0    0.415  0.356  0.806      0.8  0.031

 [21 rows x 21 columns],
 'defense':    Unnamed: 0_level_0 Unnamed: 1_level_0       Unnamed: 2_level_0  \
                  # Tm                Pos                   Player
 0                 1st                  C        Victor Wembanyama
 1                 1st                  F            Chet Holmgren
 2                 1st                  F           Ausar Thompson
 3                 1st                  C              Rudy Gobert
 4                 1st                  G            Derrick White
 5                 NaN                NaN                      NaN
 6                 2nd                  F           Scottie Barnes
 7                 2nd                  G            Cason Wallace
 8                 2nd                  C              Bam Adebayo
 9                 2nd                  F               OG Anunoby
 10                2nd                  G            Dyson Daniels
 11                NaN                NaN                      NaN
 12                ORV                  G           Stephon Castle
 13                ORV                  G            Amen Thompson
 14                ORV                  F           Draymond Green
 15                ORV                  F           Toumani Camara
 16                ORV                  G                Kris Dunn
 17                ORV                  F              Evan Mobley
 18                ORV                  F            Luguentz Dort
 19                ORV                  C              Jalen Duren
 20                ORV                  C            Neemias Queta
 21                ORV                  F             Jaylen Brown
 22                ORV                  F            Kawhi Leonard
 23                ORV                  F          Jaden McDaniels
 24                ORV                  C          Donovan Clingan
 25                ORV                  G  Shai Gilgeous-Alexander
 26                ORV                  F         Jabari Smith Jr.

    Unnamed: 3_level_0 Unnamed: 4_level_0  Voting                 \
                   Age                 Tm Pts Won Pts Max  Share
 0                22.0                SAS   200.0   200.0  1.000
 1                23.0                OKC   190.0   200.0  0.950
 2                23.0                DET   166.0   200.0  0.830
 3                33.0                MIN   151.0   200.0  0.755
 4                31.0                BOS   146.0   200.0  0.730
 5                 NaN                NaN     NaN     NaN    NaN
 6                24.0                TOR   130.0   200.0  0.650
 7                22.0                OKC    94.0   200.0  0.470
 8                28.0                MIA    71.0   200.0  0.355
 9                28.0                NYK    67.0   200.0  0.335
 10               22.0                ATL    50.0   200.0  0.250
 11                NaN                NaN     NaN     NaN    NaN
 12               21.0                SAS    46.0   200.0  0.230
 13               23.0                HOU    46.0   200.0  0.230
 14               35.0                GSW    40.0   200.0  0.200
 15               25.0                POR    28.0   200.0  0.140
 16               31.0                LAC    14.0   200.0  0.070
 17               24.0                CLE    13.0   200.0  0.065
 18               26.0                OKC    12.0   200.0  0.060
 19               22.0                DET     9.0   200.0  0.045
 20               26.0                BOS     8.0   200.0  0.040
 21               29.0                BOS     7.0   200.0  0.035
 22               34.0                LAC     5.0   200.0  0.025
 23               25.0                MIN     3.0   200.0  0.015
 24               21.0                POR     2.0   200.0  0.010
 25               27.0                OKC     1.0   200.0  0.005
 26               22.0                HOU     1.0   200.0  0.005

    Unnamed: 8_level_0 Per Game  ...           Shooting               Advanced  \
                     G       MP  ...  STL  BLK      FG%    3P%    FT%       WS
 0                64.0     29.2  ...  1.0  3.1    0.512  0.349  0.827     10.0
 1                69.0     28.9  ...  0.6  1.9    0.557  0.362  0.792      9.1
 2                73.0     26.0  ...  2.0  0.9    0.525  0.250  0.571      5.7
 3                76.0     31.3  ...  0.8  1.6    0.682  0.000  0.526      8.7
 4                77.0     34.1  ...  1.1  1.3    0.394  0.327  0.902      7.0
 5                 NaN      NaN  ...  NaN  NaN      NaN    NaN    NaN      NaN
 6                80.0     33.5  ...  1.4  1.5    0.507  0.304  0.815      7.8
 7                77.0     26.6  ...  1.9  0.4    0.432  0.351  0.809      5.2
 8                73.0     32.4  ...  1.2  0.7    0.442  0.318  0.778      6.4
 9                67.0     33.2  ...  1.6  0.7    0.484  0.386  0.828      6.3
 10               76.0     33.2  ...  2.0  0.4    0.517  0.188  0.615      6.6
 11                NaN      NaN  ...  NaN  NaN      NaN    NaN    NaN      NaN
 12               68.0     30.0  ...  1.1  0.3    0.471  0.332  0.734      5.8
 13               79.0     37.4  ...  1.5  0.6    0.534  0.216  0.779     10.3
 14               68.0     27.5  ...  0.9  0.6    0.418  0.326  0.702      1.7
 15               82.0     33.3  ...  1.1  0.4    0.440  0.370  0.708      4.8
 16               82.0     27.2  ...  1.6  0.2    0.476  0.374  0.765      4.0
 17               65.0     31.9  ...  0.7  1.7    0.546  0.297  0.606      6.5
 18               69.0     26.8  ...  0.9  0.4    0.385  0.344  0.759      3.0
 19               70.0     28.2  ...  0.8  0.8    0.650    NaN  0.747     11.0
 20               76.0     25.3  ...  0.8  1.3    0.653  0.125  0.703      9.0
 21               71.0     34.4  ...  1.0  0.4    0.477  0.347  0.795      6.9
 22               65.0     32.1  ...  1.9  0.4    0.505  0.387  0.892      9.2
 23               73.0     31.7  ...  1.1  1.0    0.515  0.412  0.835      5.2
 24               77.0     27.2  ...  0.6  1.7    0.520  0.341  0.680      8.6
 25               68.0     33.2  ...  1.4  0.8    0.553  0.386  0.879     15.2
 26               77.0     35.1  ...  0.7  0.9    0.450  0.363  0.775      6.6


     WS/48  DWS DBPM   DRtg
 0   0.257  5.0  4.2  101.0
 1   0.219  4.7  1.9  104.0
 2   0.144  4.1  3.6  105.0
 3   0.176  4.0  0.9  110.0
 4   0.129  3.5  1.0  113.0
 5     NaN  NaN  NaN    NaN
 6   0.140  4.5  2.3  110.0
 7   0.122  4.2  3.3  107.0
 8   0.129  3.6  0.4  111.0
 9   0.135  3.2  1.1  112.0
 10  0.126  3.6  1.8  112.0
 11    NaN  NaN  NaN    NaN
 12  0.136  2.9  0.9  112.0
 13  0.167  3.8  1.0  114.0
 14  0.044  2.1  1.0  115.0
 15  0.084  2.7  0.0  116.0
 16  0.085  2.3  1.5  116.0
 17  0.150  2.9  1.2  113.0
 18  0.078  3.0  0.8  110.0
 19  0.266  3.8  0.5  108.0
 20  0.224  3.6  2.0  108.0
 21  0.135  3.4 -0.1  113.0
 22  0.212  2.7  0.6  113.0
 23  0.109  2.7  0.6  114.0
 24  0.197  3.5  0.6  110.0
 25  0.323  4.1  3.0  109.0
 26  0.118  3.3 -0.2  114.0

 [27 rows x 23 columns]}

In [132]:
awards_2013["mvp"].columns.to_list()

[('Unnamed: 0_level_0', 'Rank'),
 ('Unnamed: 1_level_0', 'Player'),
 ('Unnamed: 2_level_0', 'Age'),
 ('Unnamed: 3_level_0', 'Tm'),
 ('Voting', 'First'),
 ('Voting', 'Pts Won'),
 ('Voting', 'Pts Max'),
 ('Voting', 'Share'),
 ('Unnamed: 8_level_0', 'G'),
 ('Per Game', 'MP'),
 ('Per Game', 'PTS'),
 ('Per Game', 'TRB'),
 ('Per Game', 'AST'),
 ('Per Game', 'STL'),
 ('Per Game', 'BLK'),
 ('Shooting', 'FG%'),
 ('Shooting', '3P%'),
 ('Shooting', 'FT%'),
 ('Advanced', 'WS'),
 ('Advanced', 'WS/48')]

In [149]:
### testing for only the 2001 season...



import pandas as pd
import requests
import certifi
from bs4 import BeautifulSoup, Comment
from io import StringIO


# FUNCTION 1: EXTRACT THE FIVE RAW AWARDS TABLES

def extract_awards(year):

    # A. Build URL and retrieve HTML
    url = f"https://www.basketball-reference.com/awards/awards_{year}.html"

    response = requests.get(url, verify=certifi.where(), timeout=20)
    response.raise_for_status()

    html = response.content.decode("utf-8")
    soup = BeautifulSoup(html, "html.parser")

    # B. Find visible and commented-out HTML tables
    all_tables = soup.find_all("table")

    comments = soup.find_all(
        string=lambda text: isinstance(text, Comment)
    )

    for comment in comments:
        comment_soup = BeautifulSoup(comment, "html.parser")
        all_tables.extend(comment_soup.find_all("table"))

    # C. Map award names to HTML table IDs
    table_ids = {
        "mvp": "mvp",
        "roy": "roy",
        "dpoy": "dpoy",
        "rookie": "leading_all_rookie",
        "defense": "leading_all_defense"
    }

    # D. Extract the five tables into DataFrames
    extracted = {}

    for name, table_id in table_ids.items():

        table = next(
            table for table in all_tables
            if table.get("id") == table_id
        )

        extracted[name] = pd.read_html(StringIO(str(table)))[0]

    return extracted


# FUNCTION 2: CLEAN THE FIVE DATAFRAMES

def clean_awards(raw_tables, year):

    cleaned = {}

    # A. Clean individual awards: MVP, ROY, DPOY
    for award in ["mvp", "roy", "dpoy"]:

        df = raw_tables[award].copy()
        df.columns = df.columns.get_level_values(-1)

        df = df[[
            "Rank", "Player", "Age", "Tm",
            "First", "Pts Won", "Pts Max", "Share"
        ]].copy()

        df = df.rename(columns={
            "Rank": "voting_rank",
            "Player": "player_name",
            "Age": "age",
            "Tm": "team",
            "First": "first_place_votes",
            "Pts Won": "points_won",
            "Pts Max": "points_max",
            "Share": "vote_share"
        })

        df["voting_rank"] = (
            df["voting_rank"]
            .astype(str)
            .str.replace("T", "", regex=False)
            .astype(int)
        )

        integer_columns = [
            "age", "first_place_votes",
            "points_won", "points_max"
        ]

        df[integer_columns] = df[integer_columns].astype(int)

        df["season"] = f"{year-1}-{year}"
        df["year"] = year
        df["award_winner"] = df["voting_rank"] == 1

        cleaned[award] = df

    # B. Clean team awards: All-Rookie, All-Defensive
    for award in ["rookie", "defense"]:

        df = raw_tables[award].copy()
        df.columns = df.columns.get_level_values(-1)

        df = df[df["# Tm"].isin(["1st", "2nd"])].copy()

        columns = [
            "# Tm", "Player", "Age", "Tm",
            "Pts Won", "Pts Max", "Share"
        ]

        if award == "rookie":
            columns += ["1st Tm", "2nd Tm"]
        else:
            columns += ["Pos"]

        df = df[columns].copy()

        df = df.rename(columns={
            "# Tm": "team_selection",
            "Player": "player_name",
            "Age": "age",
            "Tm": "team",
            "Pts Won": "points_won",
            "Pts Max": "points_max",
            "Share": "vote_share",
            "1st Tm": "first_team_votes",
            "2nd Tm": "second_team_votes",
            "Pos": "position"
        })

        integer_columns = ["age", "points_won", "points_max"]

        if award == "rookie":
            integer_columns += ["first_team_votes", "second_team_votes"]

        df[integer_columns] = df[integer_columns].astype(int)

        df["season"] = f"{year-1}-{year}"
        df["year"] = year

        cleaned[award] = df

    return cleaned


# RUN BOTH FUNCTIONS FOR 2001

raw_2001 = extract_awards(2001)
clean_2001 = clean_awards(raw_2001, 2001)

In [138]:
clean_2001["roy"].head()

,voting_rank,player_name,age,team,first_place_votes,points_won,points_max,vote_share,season,year,award_winner
0,1,Mike Miller,20,ORL,75,75,124,0.605,2000-2001,2001,True
1,2,Kenyon Martin,23,NJN,36,36,124,0.290,2000-2001,2001,False
2,3,Marc Jackson,26,GSW,7,7,124,0.056,2000-2001,2001,False
3,4,Darius Miles,19,LAC,3,3,124,0.024,2000-2001,2001,False
4,4,Morris Peterson,23,TOR,3,3,124,0.024,2000-2001,2001,False

In [146]:
raw_2026 = extract_awards(2026)
clean_2026 = clean_awards(raw_2026, 2026)

In [148]:
clean_2026["mvp"].head()

,voting_rank,player_name,age,team,first_place_votes,points_won,points_max,vote_share,season,year,award_winner
0,1,Shai Gilgeous-Alexander,27,OKC,83,939,1000,0.939,2025-2026,2026,True
1,2,Nikola Jokić,30,DEN,10,634,1000,0.634,2025-2026,2026,False
2,3,Victor Wembanyama,22,SAS,5,569,1000,0.569,2025-2026,2026,False
3,4,Luka Dončić,26,LAL,0,250,1000,0.250,2025-2026,2026,False
4,5,Cade Cunningham,24,DET,2,117,1000,0.117,2025-2026,2026,False

In [166]:

from pathlib import Path
import time

def build_awards_history(start_year=2001, end_year=2026):

    award_names = ["mvp", "roy", "dpoy", "rookie", "defense"]

    # Track cleaned DataFrames for final concatenation
    cleaned_history = {award: [] for award in award_names}

    failed_years = []

    for year in range(start_year, end_year + 1):

        print(f"Processing {year}...")

        raw_folder = PROJECT_ROOT / "data" / "raw" / "awards" / str(year)
        staging_folder = PROJECT_ROOT / "data" / "staging" / "awards" / str(year)


        raw_folder.mkdir(parents=True, exist_ok=True)
        staging_folder.mkdir(parents=True, exist_ok=True)
        
        try:
            # 1. Extract five raw DataFrames
            raw = extract_awards(year)

            # 2. Clean five DataFrames
            cleaned = clean_awards(raw, year)

            # 3. Save both raw and cleaned tables
            for award in award_names:

                raw[award].to_csv(
                    raw_folder / f"{award}.csv",
                    index=False,
                    encoding="utf-8"
                )

                cleaned[award].to_csv(
                    staging_folder / f"{award}.csv",
                    index=False,
                    encoding="utf-8"
                )

                # Collect cleaned DataFrames
                cleaned_history[award].append(cleaned[award])

            print(f"Completed {year}")

        except Exception as e:
            failed_years.append(year)
            print(f"Failed {year}: {e}")

        # Pause between requests
        if year < end_year:
            time.sleep(5)

    # 4. Concatenate all successfully cleaned seasons
    historical_awards = {}

    output_folder = PROJECT_ROOT / "data" / "staging" / "awards"
    output_folder.mkdir(parents=True, exist_ok=True)

    for award in award_names:

        if cleaned_history[award]:

            historical_awards[award] = pd.concat(
                cleaned_history[award],
                ignore_index=True
            )

            historical_awards[award].to_csv(
                output_folder / f"{award}_history.csv",
                index=False,
                encoding="utf-8"
            )

    print("Finished processing.")
    print("Failed years:", failed_years)

    return historical_awards, failed_years

In [167]:
historical_awards, failed_years = build_awards_history(
    start_year=2001,
    end_year=2002
)

Processing 2001...
Completed 2001
Processing 2002...
Completed 2002
Finished processing.
Failed years: []

In [168]:
historical_awards

{'mvp':     voting_rank       player_name  age team  first_place_votes  points_won  \
 0             1     Allen Iverson   25  PHI                 93        1121
 1             2        Tim Duncan   24  SAS                 18         706
 2             3  Shaquille O'Neal   28  LAL                  7         578
 3             4      Chris Webber   27  SAC                  5         521
 4             5     Kevin Garnett   24  MIN                  1         151
 5             6     Tracy McGrady   21  ORL                  0          64
 6             7       Karl Malone   37  UTA                  0          21
 7             8        Jason Kidd   27  PHO                  0          18
 8             9       Kobe Bryant   22  LAL                  0          11
 9            10    David Robinson   35  SAS                  0           8
 10           11         Ray Allen   25  MIL                  0           7
 11           11      Vince Carter   24  TOR                  0           7
 12           13       Paul Pierce   23  BOS                  0           5
 13           14  Jerry Stackhouse   26  DET                  0           3
 14           15    Michael Finley   27  DAL                  0           1
 15           15     Anthony Mason   34  MIA                  0           1
 16           15     John Stockton   38  UTA                  0           1
 17            1        Tim Duncan   25  SAS                 57         954
 18            2        Jason Kidd   28  NJN                 45         897
 19            3  Shaquille O'Neal   29  LAL                 15         696
 20            4     Tracy McGrady   22  ORL                  7         390
 21            5       Kobe Bryant   23  LAL                  1          98
 22            6       Gary Payton   33  SEA                  1          54
 23            7      Chris Webber   28  SAC                  0          37
 24            8     Dirk Nowitzki   23  DAL                  0          31
 25            9     Allen Iverson   26  PHI                  0          29
 26           10       Ben Wallace   27  DET                  0          24
 27           11       Paul Pierce   24  BOS                  0          22
 28           12     Kevin Garnett   25  MIN                  0          17
 29           13    Michael Jordan   38  WAS                  0          16
 30           14        Steve Nash   27  DAL                  0           5
 31           15  Jerry Stackhouse   27  DET                  0           3
 32           16        Mike Bibby   23  SAC                  0           1
 33           16       Elton Brand   22  LAC                  0           1
 34           16   Peja Stojaković   24  SAC                  0           1

     points_max  vote_share     season  year  award_winner
 0         1240       0.904  2000-2001  2001          True
 1         1240       0.569  2000-2001  2001         False
 2         1240       0.466  2000-2001  2001         False
 3         1240       0.420  2000-2001  2001         False
 4         1240       0.122  2000-2001  2001         False
 5         1240       0.052  2000-2001  2001         False
 6         1240       0.017  2000-2001  2001         False
 7         1240       0.015  2000-2001  2001         False
 8         1240       0.009  2000-2001  2001         False
 9         1240       0.006  2000-2001  2001         False
 10        1240       0.006  2000-2001  2001         False
 11        1240       0.006  2000-2001  2001         False
 12        1240       0.004  2000-2001  2001         False
 13        1240       0.002  2000-2001  2001         False
 14        1240       0.001  2000-2001  2001         False
 15        1240       0.001  2000-2001  2001         False
 16        1240       0.001  2000-2001  2001         False
 17        1260       0.757  2001-2002  2002          True
 18        1260       0.712  2001-2002  2002         False
 19        1260       0.552  2001-2002  2002         False
 20        1260       0.310  2001-2002  2002         False
 21        1260       0.078  2001-2002  2002         False
 22        1260       0.043  2001-2002  2002         False
 23        1260       0.029  2001-2002  2002         False
 24        1260       0.025  2001-2002  2002         False
 25        1260       0.023  2001-2002  2002         False
 26        1260       0.019  2001-2002  2002         False
 27        1260       0.017  2001-2002  2002         False
 28        1260       0.013  2001-2002  2002         False
 29        1260       0.013  2001-2002  2002         False
 30        1260       0.004  2001-2002  2002         False
 31        1260       0.002  2001-2002  2002         False
 32        1260       0.001  2001-2002  2002         False
 33        1260       0.001  2001-2002  2002         False
 34        1260       0.001  2001-2002  2002         False  ,
 'roy':    voting_rank        player_name  age team  first_place_votes  points_won  \
 0            1        Mike Miller   20  ORL                 75          75
 1            2      Kenyon Martin   23  NJN                 36          36
 2            3       Marc Jackson   26  GSW                  7           7
 3            4       Darius Miles   19  LAC                  3           3
 4            4    Morris Peterson   23  TOR                  3           3
 5            1          Pau Gasol   21  MEM                117         117
 6            2  Richard Jefferson   21  NJN                  3           3
 7            3   Andrei Kirilenko   20  UTA                  2           2
 8            3   Jason Richardson   21  GSW                  2           2
 9            3     Jamaal Tinsley   23  IND                  2           2

    points_max  vote_share     season  year  award_winner
 0         124       0.605  2000-2001  2001          True
 1         124       0.290  2000-2001  2001         False
 2         124       0.056  2000-2001  2001         False
 3         124       0.024  2000-2001  2001         False
 4         124       0.024  2000-2001  2001         False
 5         126       0.929  2001-2002  2002          True
 6         126       0.024  2001-2002  2002         False
 7         126       0.016  2001-2002  2002         False
 8         126       0.016  2001-2002  2002         False
 9         126       0.016  2001-2002  2002         False  ,
 'dpoy':     voting_rank       player_name  age team  first_place_votes  points_won  \
 0             1   Dikembe Mutombo   34  TOT                 48          48
 1             2     Kevin Garnett   24  MIN                 26          26
 2             3        Tim Duncan   24  SAS                 14          14
 3             4     Doug Christie   30  SAC                  9           9
 4             5    David Robinson   35  SAS                  6           6
 5             5       Ben Wallace   26  DET                  6           6
 6             7      Theo Ratliff   27  PHI                  4           4
 7             8       Bruce Bowen   29  MIA                  2           2
 8             8     Anthony Mason   34  MIA                  2           2
 9             8  Shaquille O'Neal   28  LAL                  2           2
 10           11       Kobe Bryant   22  LAL                  1           1
 11           11     Allen Iverson   25  PHI                  1           1
 12           11        Jason Kidd   27  PHO                  1           1
 13           11      Shawn Marion   22  PHO                  1           1
 14            1       Ben Wallace   27  DET                116         116
 15            2     Kevin Garnett   25  MIN                  2           2
 16            3       Kobe Bryant   23  LAL                  1           1
 17            3   Dikembe Mutombo   35  PHI                  1           1

     points_max  vote_share     season  year  award_winner
 0          123       0.390  2000-2001  2001          True
 1          123       0.211  2000-2001  2001         False
 2          123       0.114  2000-2001  2001         False
 3          123       0.073  2000-2001  2001         False
 4          123       0.049  2000-2001  2001         False
 5          123       0.049  2000-2001  2001         False
 6          123       0.033  2000-2001  2001         False
 7          123       0.016  2000-2001  2001         False
 8          123       0.016  2000-2001  2001         False
 9          123       0.016  2000-2001  2001         False
 10         123       0.008  2000-2001  2001         False
 11         123       0.008  2000-2001  2001         False
 12         123       0.008  2000-2001  2001         False
 13         123       0.008  2000-2001  2001         False
 14         120       0.967  2001-2002  2002          True
 15         120       0.017  2001-2002  2002         False
 16         120       0.008  2001-2002  2002         False
 17         120       0.008  2001-2002  2002         False  ,
 'rookie':    team_selection          player_name  age team  points_won  points_max  \
 0             1st          Mike Miller   20  ORL          56          56
 1             1st        Kenyon Martin   23  NJN          54          56
 2             1st         Marc Jackson   26  GSW          51          56
 3             1st      Morris Peterson   23  TOR          50          56
 4             1st         Darius Miles   19  LAC          48          56
 5             2nd        Hedo Türkoğlu   21  SAC          34          56
 6             2nd        Desmond Mason   23  SEA          28          56
 7             2nd         Marcus Fizer   22  CHI          16          56
 8             2nd           Chris Mihm   21  CLE          13          56
 9             1st            Pau Gasol   21  MEM          56          56
 10            1st        Shane Battier   23  MEM          54          56
 11            1st     Jason Richardson   21  GSW          53          56
 12            1st          Tony Parker   19  SAS          48          56
 13            1st     Andrei Kirilenko   20  UTA          45          56
 14            2nd       Jamaal Tinsley   23  IND          43          56
 15            2nd    Richard Jefferson   21  NJN          35          56
 16            2nd        Eddie Griffin   19  HOU          21          56
 17            2nd       Željko Rebrača   29  DET          15          56
 18            2nd  Vladimir Radmanović   21  SEA          11          56

     vote_share  first_team_votes  second_team_votes     season  year
 0        1.000                28                  0  2000-2001  2001
 1        0.964                27                  0  2000-2001  2001
 2        0.911                24                  3  2000-2001  2001
 3        0.893                22                  6  2000-2001  2001
 4        0.857                21                  6  2000-2001  2001
 5        0.607                 9                 16  2000-2001  2001
 6        0.500                 5                 18  2000-2001  2001
 7        0.286                 1                 14  2000-2001  2001
 8        0.232                 1                 11  2000-2001  2001
 9        1.000                28                  0  2001-2002  2002
 10       0.964                26                  2  2001-2002  2002
 11       0.946                25                  3  2001-2002  2002
 12       0.857                20                  8  2001-2002  2002
 13       0.804                18                  9  2001-2002  2002
 14       0.768                15                 13  2001-2002  2002
 15       0.625                 8                 19  2001-2002  2002
 16       0.375                 2                 17  2001-2002  2002
 17       0.268                 2                 11  2001-2002  2002
 18       0.196                 1                  9  2001-2002  2002  ,
 'defense':    team_selection        player_name  age team  points_won  points_max  \
 0             1st    Dikembe Mutombo   34  TOT          43          58
 1             1st         Tim Duncan   24  SAS          40          58
 2             1st         Jason Kidd   27  PHO          39          58
 3             1st        Gary Payton   32  SEA          38          58
 4             1st      Kevin Garnett   24  MIN          24          58
 5             2nd        Kobe Bryant   22  LAL          26          58
 6             2nd      Doug Christie   30  SAC          20          58
 7             2nd        Bruce Bowen   29  MIA          18          58
 8             2nd   Shaquille O'Neal   28  LAL          17          58
 9             2nd         P.J. Brown   31  CHH          13          58
 10            1st        Ben Wallace   27  DET          51          58
 11            1st        Gary Payton   33  SEA          47          58
 12            1st         Tim Duncan   25  SAS          40          58
 13            1st         Jason Kidd   28  NJN          37          58
 14            1st      Kevin Garnett   25  MIN          27          58
 15            2nd        Kobe Bryant   23  LAL          32          58
 16            2nd    Dikembe Mutombo   35  PHI          27          58
 17            2nd      Doug Christie   31  SAC          25          58
 18            2nd        Bruce Bowen   30  SAS          21          58
 19            2nd  Clifford Robinson   35  DET          14          58

     vote_share position     season  year
 0        0.741        C  2000-2001  2001
 1        0.690        F  2000-2001  2001
 2        0.672        G  2000-2001  2001
 3        0.655        G  2000-2001  2001
 4        0.414        F  2000-2001  2001
 5        0.448        G  2000-2001  2001
 6        0.345        G  2000-2001  2001
 7        0.310        F  2000-2001  2001
 8        0.293        C  2000-2001  2001
 9        0.224        F  2000-2001  2001
 10       0.879        C  2001-2002  2002
 11       0.810        G  2001-2002  2002
 12       0.690        F  2001-2002  2002
 13       0.638        G  2001-2002  2002
 14       0.466        F  2001-2002  2002
 15       0.552        G  2001-2002  2002
 16       0.466        C  2001-2002  2002
 17       0.431        G  2001-2002  2002
 18       0.362        F  2001-2002  2002
 19       0.241        F  2001-2002  2002  }

In [169]:
for award, df in historical_awards.items():
    print(award, df.shape, df["year"].unique())

mvp (35, 11) [2001 2002]
roy (10, 11) [2001 2002]
dpoy (18, 11) [2001 2002]
rookie (19, 11) [2001 2002]
defense (20, 10) [2001 2002]

In [172]:
historical_awards["dpoy"].head()

,voting_rank,player_name,age,team,first_place_votes,points_won,points_max,vote_share,season,year,award_winner
0,1,Dikembe Mutombo,34,TOT,48,48,123,0.390,2000-2001,2001,True
1,2,Kevin Garnett,24,MIN,26,26,123,0.211,2000-2001,2001,False
2,3,Tim Duncan,24,SAS,14,14,123,0.114,2000-2001,2001,False
3,4,Doug Christie,30,SAC,9,9,123,0.073,2000-2001,2001,False
4,5,David Robinson,35,SAS,6,6,123,0.049,2000-2001,2001,False

In [173]:
historical_awards, failed_years = build_awards_history(
    start_year=2001,
    end_year=2026
)

Processing 2001...
Completed 2001
Processing 2002...
Completed 2002
Processing 2003...
Completed 2003
Processing 2004...
Completed 2004
Processing 2005...
Completed 2005
Processing 2006...
Completed 2006
Processing 2007...
Completed 2007
Processing 2008...
Completed 2008
Processing 2009...
Completed 2009
Processing 2010...
Completed 2010
Processing 2011...
Completed 2011
Processing 2012...
Completed 2012
Processing 2013...
Completed 2013
Processing 2014...
Completed 2014
Processing 2015...
Completed 2015
Processing 2016...
Completed 2016
Processing 2017...
Completed 2017
Processing 2018...
Completed 2018
Processing 2019...
Completed 2019
Processing 2020...
Completed 2020
Processing 2021...
Completed 2021
Processing 2022...
Completed 2022
Processing 2023...
Completed 2023
Processing 2024...
Completed 2024
Processing 2025...
Completed 2025
Processing 2026...
Completed 2026
Finished processing.
Failed years: []

In [174]:
from pathlib import Path

award_names = ["mvp", "roy", "dpoy", "rookie", "defense"]
expected_years = set(range(2001, 2027))

print("FAILED YEARS:", failed_years)
print()

for award in award_names:

    df = historical_awards.get(award)

    if df is None:
        print(f"{award}: MISSING HISTORICAL DATAFRAME")
        continue

    actual_years = set(df["year"].dropna().astype(int))
    missing_years = sorted(expected_years - actual_years)

    raw_count = sum(
        (PROJECT_ROOT / "data" / "raw" / "awards" /
         str(year) / f"{award}.csv").is_file()
        for year in expected_years
    )

    staging_count = sum(
        (PROJECT_ROOT / "data" / "staging" / "awards" /
         str(year) / f"{award}.csv").is_file()
        for year in expected_years
    )

    history_exists = (
        PROJECT_ROOT / "data" / "staging" / "awards" /
        f"{award}_history.csv"
    ).is_file()

    print(f"AWARD: {award}")
    print("  Total rows:", len(df))
    print("  Seasons:", len(actual_years), "/ 26")
    print("  Missing seasons:", missing_years)
    print("  Raw CSVs:", raw_count, "/ 26")
    print("  Staging CSVs:", staging_count, "/ 26")
    print("  Historical CSV exists:", history_exists)
    print("  Duplicate rows:", df.duplicated().sum())
    print()

FAILED YEARS: []

AWARD: mvp
  Total rows: 352
  Seasons: 26 / 26
  Missing seasons: []
  Raw CSVs: 26 / 26
  Staging CSVs: 26 / 26
  Historical CSV exists: True
  Duplicate rows: 0

AWARD: roy
  Total rows: 198
  Seasons: 26 / 26
  Missing seasons: []
  Raw CSVs: 26 / 26
  Staging CSVs: 26 / 26
  Historical CSV exists: True
  Duplicate rows: 0

AWARD: dpoy
  Total rows: 426
  Seasons: 26 / 26
  Missing seasons: []
  Raw CSVs: 26 / 26
  Staging CSVs: 26 / 26
  Historical CSV exists: True
  Duplicate rows: 0

AWARD: rookie
  Total rows: 260
  Seasons: 26 / 26
  Missing seasons: []
  Raw CSVs: 26 / 26
  Staging CSVs: 26 / 26
  Historical CSV exists: True
  Duplicate rows: 0

AWARD: defense
  Total rows: 263
  Seasons: 26 / 26
  Missing seasons: []
  Raw CSVs: 26 / 26
  Staging CSVs: 26 / 26
  Historical CSV exists: True
  Duplicate rows: 0