In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path("/Users/jonathantran/Desktop/nba_economics")

STAGING_DIR = PROJECT_ROOT / "data" / "staging"
CANONICAL_DIR = PROJECT_ROOT / "data" / "canonical"

In [2]:
for source in ["s04", "s05", "s06"]:
    matches = sorted(
        p for p in STAGING_DIR.rglob("*.csv")
        if source in p.name.lower()
    )

    print(f"\n{source.upper()}:")
    for path in matches:
        print(" ", path.relative_to(STAGING_DIR))

S04:
  rosters/s04_rosters.csv

S05:
  player_stats/s05_player_stats.csv

S06:
  advanced_player_stats/s06_advanced_player_stats.csv

In [3]:
print("Kernel is working")

Kernel is working

In [4]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path("/Users/jonathantran/Desktop/nba_economics")
STAGING_DIR = PROJECT_ROOT / "data" / "staging"
CANONICAL_DIR = PROJECT_ROOT / "data" / "canonical"

for source in ["s04", "s05", "s06"]:
    matches = sorted(
        p for p in STAGING_DIR.rglob("*.csv")
        if source in p.name.lower()
    )

    print(f"\n{source.upper()}:")
    for path in matches:
        print(" ", path.relative_to(STAGING_DIR))

S04:
  rosters/s04_rosters.csv

S05:
  player_stats/s05_player_stats.csv

S06:
  advanced_player_stats/s06_advanced_player_stats.csv

In [5]:
sources = {}

for source in ["s04", "s05", "s06"]:
    matches = [
        p for p in STAGING_DIR.rglob("*.csv")
        if source in p.name.lower()
    ]

    assert len(matches) == 1, (
        f"{source}: expected 1 file, found {len(matches)}"
    )

    sources[source] = pd.read_csv(matches[0])

s04 = sources["s04"]
s05 = sources["s05"]
s06 = sources["s06"]

for name, df in sources.items():
    print(f"\n{name.upper()}")
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print("Seasons:", df["season"].nunique() if "season" in df.columns else "Check season column")
    display(df.head(3))

S04
Shape: (12810, 25)
Columns: ['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'PLAYER_HEIGHT', 'PLAYER_HEIGHT_INCHES', 'PLAYER_WEIGHT', 'COLLEGE', 'COUNTRY', 'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER', 'GP', 'PTS', 'REB', 'AST', 'NET_RATING', 'OREB_PCT', 'DREB_PCT', 'USG_PCT', 'TS_PCT', 'AST_PCT', 'season', 'year']
Seasons: 26

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,PLAYER_HEIGHT,PLAYER_HEIGHT_INCHES,PLAYER_WEIGHT,COLLEGE,COUNTRY,...,REB,AST,NET_RATING,OREB_PCT,DREB_PCT,USG_PCT,TS_PCT,AST_PCT,season,year
0,920,A.C. Green,1610612748,MIA,37.0,6-9,81.0,225,Oregon State,USA,...,313,39,3.8,0.076,0.151,0.137,0.492,0.050,2000-2001,2001
1,2062,A.J. Guyton,1610612741,CHI,23.0,6-1,73.0,180,Indiana,USA,...,36,64,-11.0,0.016,0.046,0.167,0.495,0.198,2000-2001,2001
2,243,Aaron McKie,1610612755,PHI,28.0,6-5,77.0,209,Temple,USA,...,311,377,7.3,0.015,0.115,0.186,0.549,0.264,2000-2001,2001

S05
Shape: (12810, 31)
Columns: ['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PTS', 'PLUS_MINUS', 'season', 'year']
Seasons: 26

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,...,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS,season,year
0,920,A.C. Green,1610612748,MIA,37.0,82,50,32,0.610,17.2,...,3.8,0.5,0.5,0.4,0.1,1.5,4.5,1.3,2000-2001,2001
1,2062,A.J. Guyton,1610612741,CHI,23.0,33,6,27,0.182,19.0,...,1.1,1.9,0.7,0.3,0.2,1.1,6.0,-4.4,2000-2001,2001
2,243,Aaron McKie,1610612755,PHI,28.0,76,51,25,0.671,31.5,...,4.1,5.0,2.7,1.4,0.1,2.3,11.6,4.4,2000-2001,2001

S06
Shape: (12810, 23)
Columns: ['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'MIN', 'OFF_RATING', 'DEF_RATING', 'NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'USG_PCT', 'PACE', 'PIE', 'POSS', 'season', 'year']
Seasons: 26

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,MIN,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,...,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,PACE,PIE,POSS,season,year
0,920,A.C. Green,1610612748,MIA,17.2,94.1,90.4,3.8,0.050,0.87,...,0.113,9.9,0.444,0.492,0.137,90.37,0.093,2660,2000-2001,2001
1,2062,A.J. Guyton,1610612741,CHI,19.0,92.0,102.9,-11.0,0.198,2.67,...,0.030,8.3,0.477,0.495,0.167,90.19,0.071,1173,2000-2001,2001
2,243,Aaron McKie,1610612755,PHI,31.5,102.7,95.5,7.3,0.264,1.86,...,0.066,14.7,0.511,0.549,0.186,93.17,0.119,4639,2000-2001,2001

In [6]:
keys = ["PLAYER_ID", "TEAM_ID", "season"]

for name, df in sources.items():

    print(f"\n{'=' * 55}")
    print(name.upper())
    print(f"{'=' * 55}")

    print("Total rows:", len(df))

    print(
        "Unique player-team-seasons:",
        df[keys].drop_duplicates().shape[0]
    )

    print(
        "Duplicate player-team-season keys:",
        df.duplicated(keys).sum()
    )

    print(
        "Unique player-seasons:",
        df[["PLAYER_ID", "season"]]
        .drop_duplicates()
        .shape[0]
    )

    print(
        "Missing key values:",
        df[keys].isna().sum().to_dict()
    )

    print(
        "Unique players:",
        df["PLAYER_ID"].nunique()
    )

    print(
        "Unique teams:",
        df["TEAM_ID"].nunique()
    )

=======================================================
S04
=======================================================
Total rows: 12810
Unique player-team-seasons: 12810
Duplicate player-team-season keys: 0
Unique player-seasons: 12810
Missing key values: {'PLAYER_ID': 0, 'TEAM_ID': 0, 'season': 0}
Unique players: 2584
Unique teams: 30

=======================================================
S05
=======================================================
Total rows: 12810
Unique player-team-seasons: 12810
Duplicate player-team-season keys: 0
Unique player-seasons: 12810
Missing key values: {'PLAYER_ID': 0, 'TEAM_ID': 0, 'season': 0}
Unique players: 2584
Unique teams: 30

=======================================================
S06
=======================================================
Total rows: 12810
Unique player-team-seasons: 12810
Duplicate player-team-season keys: 0
Unique player-seasons: 12810
Missing key values: {'PLAYER_ID': 0, 'TEAM_ID': 0, 'season': 0}
Unique players: 2584
Unique teams: 30

In [7]:
player_team_counts = (
    s04.groupby(["PLAYER_ID", "season"])["TEAM_ID"]
    .nunique()
    .reset_index(name="team_count")
)

multi_team_players = player_team_counts[
    player_team_counts["team_count"] > 1
]

print(
    "Player-seasons involving multiple teams:",
    len(multi_team_players)
)

print(
    "Maximum teams for one player in one season:",
    player_team_counts["team_count"].max()
)

display(multi_team_players.head(10))

Player-seasons involving multiple teams: 0
Maximum teams for one player in one season: 1

Empty DataFrame
Columns: [PLAYER_ID, season, team_count]
Index: []

In [8]:
keys = ["PLAYER_ID", "TEAM_ID", "season"]

for name in ["s05", "s06"]:

    comparison = s04[keys].merge(
        sources[name][keys],
        on=keys,
        how="outer",
        indicator=True,
        validate="one_to_one"
    )

    print(f"\nS04 vs {name.upper()}")
    print(comparison["_merge"].value_counts())

S04 vs S05
_merge
both          12810
left_only         0
right_only        0
Name: count, dtype: int64

S04 vs S06
_merge
both          12810
left_only         0
right_only        0
Name: count, dtype: int64

In [9]:
# Compare overlapping S04 and S06 advanced statistics.

advanced_cols = [
    "NET_RATING",
    "OREB_PCT",
    "DREB_PCT",
    "USG_PCT",
    "TS_PCT",
    "AST_PCT"
]

keys = ["PLAYER_ID", "TEAM_ID", "season"]

advanced_check = s04[
    keys + advanced_cols
].merge(
    s06[keys + advanced_cols],
    on=keys,
    how="inner",
    validate="one_to_one",
    suffixes=("_s04", "_s06")
)

for col in advanced_cols:
    left = advanced_check[f"{col}_s04"]
    right = advanced_check[f"{col}_s06"]

    mismatches = (
        left.ne(right)
        & ~(left.isna() & right.isna())
    ).sum()

    print(f"{col}: {mismatches} mismatches")

NET_RATING: 0 mismatches
OREB_PCT: 0 mismatches
DREB_PCT: 0 mismatches
USG_PCT: 0 mismatches
TS_PCT: 0 mismatches
AST_PCT: 0 mismatches

In [10]:
totals_check = s04[
    keys + ["GP", "PTS", "REB", "AST"]
].merge(
    s05[
        keys + ["GP", "PTS", "REB", "AST"]
    ],
    on=keys,
    validate="one_to_one",
    suffixes=("_total", "_per_game")
)

for stat in ["PTS", "REB", "AST"]:
    estimated_total = (
        totals_check[f"{stat}_per_game"]
        * totals_check["GP_per_game"]
    )

    difference = (
        totals_check[f"{stat}_total"] - estimated_total
    ).abs()

    print(
        f"{stat}:",
        "within 0.5 per game played:",
        (difference <= 0.5 * totals_check["GP_per_game"]).mean()
    )

print(
    "Games played mismatches:",
    (
        totals_check["GP_total"]
        != totals_check["GP_per_game"]
    ).sum()
)

PTS: within 0.5 per game played: 1.0
REB: within 0.5 per game played: 1.0
AST: within 0.5 per game played: 1.0
Games played mismatches: 0

In [11]:
# C05: Player-season performance with recorded franchise assignment
# Sources: S04 roster, S05 traditional stats, S06 advanced stats

keys = ["PLAYER_ID", "TEAM_ID", "season"]

# 1. S04: identity, physical characteristics, and season totals.
# Biographical fields already live in C03, so we don't duplicate them here.
roster = s04[
    keys + [
        "AGE",
        "PLAYER_HEIGHT_INCHES",
        "PLAYER_WEIGHT",
        "GP",
        "PTS",
        "REB",
        "AST"
    ]
].rename(columns={
    "PLAYER_ID": "player_id",
    "TEAM_ID": "franchise_id",
    "AGE": "age",
    "PLAYER_HEIGHT_INCHES": "height_inches",
    "PLAYER_WEIGHT": "weight_lbs",
    "GP": "games_played",
    "PTS": "points_total",
    "REB": "rebounds_total",
    "AST": "assists_total"
})

# 2. S05: traditional performance statistics.
# MIN and scoring/rebounding statistics are per-game averages.
traditional = s05[
    keys + [
        "W", "L", "W_PCT", "MIN",
        "FGM", "FGA", "FG_PCT",
        "FG3M", "FG3A", "FG3_PCT",
        "FTM", "FTA", "FT_PCT",
        "OREB", "DREB", "REB", "AST",
        "TOV", "STL", "BLK", "PF",
        "PTS", "PLUS_MINUS"
    ]
].rename(columns={
    "PLAYER_ID": "player_id",
    "TEAM_ID": "franchise_id",
    "W": "wins",
    "L": "losses",
    "W_PCT": "win_pct",
    "MIN": "minutes_per_game",
    "FGM": "field_goals_made_per_game",
    "FGA": "field_goals_attempted_per_game",
    "FG_PCT": "field_goal_pct",
    "FG3M": "three_pointers_made_per_game",
    "FG3A": "three_pointers_attempted_per_game",
    "FG3_PCT": "three_point_pct",
    "FTM": "free_throws_made_per_game",
    "FTA": "free_throws_attempted_per_game",
    "FT_PCT": "free_throw_pct",
    "OREB": "offensive_rebounds_per_game",
    "DREB": "defensive_rebounds_per_game",
    "REB": "rebounds_per_game",
    "AST": "assists_per_game",
    "TOV": "turnovers_per_game",
    "STL": "steals_per_game",
    "BLK": "blocks_per_game",
    "PF": "personal_fouls_per_game",
    "PTS": "points_per_game",
    "PLUS_MINUS": "plus_minus_per_game"
})

# 3. S06: advanced performance statistics.
# Overlapping S04 advanced fields were validated as identical.
advanced = s06[
    keys + [
        "OFF_RATING", "DEF_RATING", "NET_RATING",
        "AST_PCT", "AST_TO", "AST_RATIO",
        "OREB_PCT", "DREB_PCT", "REB_PCT",
        "TM_TOV_PCT", "EFG_PCT", "TS_PCT",
        "USG_PCT", "PACE", "PIE", "POSS"
    ]
].rename(columns={
    "PLAYER_ID": "player_id",
    "TEAM_ID": "franchise_id",
    "OFF_RATING": "offensive_rating",
    "DEF_RATING": "defensive_rating",
    "NET_RATING": "net_rating",
    "AST_PCT": "assist_pct",
    "AST_TO": "assist_to_turnover_ratio",
    "AST_RATIO": "assist_ratio",
    "OREB_PCT": "offensive_rebound_pct",
    "DREB_PCT": "defensive_rebound_pct",
    "REB_PCT": "rebound_pct",
    "TM_TOV_PCT": "team_turnover_pct",
    "EFG_PCT": "effective_field_goal_pct",
    "TS_PCT": "true_shooting_pct",
    "USG_PCT": "usage_pct",
    "PACE": "pace",
    "PIE": "player_impact_estimate",
    "POSS": "possessions"
})

# 4. Merge the three validated source tables.
canonical_keys = ["player_id", "franchise_id", "season"]

player_team_seasons = (
    roster
    .merge(
        traditional,
        on=canonical_keys,
        how="left",
        validate="one_to_one"
    )
    .merge(
        advanced,
        on=canonical_keys,
        how="left",
        validate="one_to_one"
    )
)

print("Shape:", player_team_seasons.shape)
display(player_team_seasons.head(3))

Shape: (12810, 49)

,player_id,franchise_id,season,age,height_inches,weight_lbs,games_played,points_total,rebounds_total,assists_total,...,offensive_rebound_pct,defensive_rebound_pct,rebound_pct,team_turnover_pct,effective_field_goal_pct,true_shooting_pct,usage_pct,pace,player_impact_estimate,possessions
0,920,1610612748,2000-2001,37.0,81.0,225,82,367,313,39,...,0.076,0.151,0.113,9.9,0.444,0.492,0.137,90.37,0.093,2660
1,2062,1610612741,2000-2001,23.0,73.0,180,33,198,36,64,...,0.016,0.046,0.030,8.3,0.477,0.495,0.167,90.19,0.071,1173
2,243,1610612755,2000-2001,28.0,77.0,209,76,878,311,377,...,0.015,0.115,0.066,14.7,0.511,0.549,0.186,93.17,0.119,4639

In [12]:
# Load canonical reference tables.
players = pd.read_csv(CANONICAL_DIR / "players.csv")
aliases = pd.read_csv(
    CANONICAL_DIR / "franchise_season_aliases.csv"
)

# Primary-key checks.
key_cols = ["player_id", "franchise_id", "season"]

print("Total rows:", len(player_team_seasons))
print("Duplicate primary keys:", player_team_seasons.duplicated(key_cols).sum())
print("Duplicate player-seasons:",
      player_team_seasons.duplicated(["player_id", "season"]).sum())
print("Missing primary-key values:",
      player_team_seasons[key_cols].isna().sum().to_dict())

# Verify player identities against C03.
unmatched_players = ~player_team_seasons["player_id"].isin(
    players["player_id"]
)

print("Unmatched player IDs:", unmatched_players.sum())

# Verify franchise-season assignments against C02.
franchise_check = player_team_seasons[
    ["franchise_id", "season"]
].merge(
    aliases[["franchise_id", "season"]],
    on=["franchise_id", "season"],
    how="left",
    indicator=True,
    validate="many_to_one"
)

print("Franchise-season mapping:")
print(franchise_check["_merge"].value_counts())

# Check that the source joins produced no missing performance records.
print(
    "Missing traditional statistics:",
    player_team_seasons["games_played"].notna().sum()
    - player_team_seasons["points_per_game"].notna().sum()
)

print(
    "Missing advanced statistics:",
    player_team_seasons["offensive_rating"].isna().sum()
)

print("Seasons:", player_team_seasons["season"].nunique())
print("Columns:", len(player_team_seasons.columns))

Total rows: 12810
Duplicate primary keys: 0
Duplicate player-seasons: 0
Missing primary-key values: {'player_id': 0, 'franchise_id': 0, 'season': 0}
Unmatched player IDs: 0
Franchise-season mapping:
_merge
both          12810
left_only         0
right_only        0
Name: count, dtype: int64
Missing traditional statistics: 0
Missing advanced statistics: 0
Seasons: 26
Columns: 49

In [13]:
# Final assertions
assert len(player_team_seasons) == 12810
assert not player_team_seasons.duplicated(
    ["player_id", "franchise_id", "season"]
).any()

assert not player_team_seasons[
    ["player_id", "franchise_id", "season"]
].isna().any().any()

assert unmatched_players.sum() == 0
assert (franchise_check["_merge"] == "both").all()

# Export
CANONICAL_DIR.mkdir(parents=True, exist_ok=True)

output_path = CANONICAL_DIR / "player_team_seasons.csv"

player_team_seasons.to_csv(output_path, index=False)

print("C05 exported:", output_path)
print("Shape:", player_team_seasons.shape)

C05 exported: /Users/jonathantran/Desktop/nba_economics/data/canonical/player_team_seasons.csv
Shape: (12810, 49)